
import type { Exercise } from '@/types';

export const PRELOADED_EXERCISES: Exercise[] = [
  {
    id: 'bench-press',
    name: 'Bench Press',
    emoji: '🏋️',
    muscleGroup: 'Chest',
    secondaryMuscleGroups: ['Shoulders', 'Triceps'],
    workoutType: ['Strength', 'Hypertrophy', 'Powerlifting', 'Bodybuilding'],
    description: 'A compound exercise that targets the chest, shoulders, and triceps. Lie on a bench and lower a barbell to your chest, then press it back up.',
    instructions: [
      'Lie flat on a bench with your feet firmly on the ground.',
      'Grip the barbell with hands slightly wider than shoulder-width apart.',
      'Lower the bar slowly to your mid-chest, keeping your elbows tucked at about a 45-degree angle.',
      'Press the bar back up until your arms are fully extended, without locking your elbows.',
    ],
    tips: ['Keep your glutes on the bench and maintain a slight arch in your lower back.', 'Control the weight throughout the movement.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'squat',
    name: 'Barbell Squat',
    emoji: '🦵',
    muscleGroup: 'Legs',
    secondaryMuscleGroups: ['Glutes', 'Back'],
    workoutType: ['Strength', 'Hypertrophy', 'Powerlifting', 'Bodybuilding'],
    description: 'A fundamental compound exercise that primarily targets the quadriceps, hamstrings, and glutes. Involves squatting down with a barbell on your upper back.',
    instructions: [
      'Stand with your feet shoulder-width apart, toes pointing slightly outwards.',
      'Rest the barbell on your upper back (traps), not on your neck.',
      'Keeping your chest up and back straight, lower your hips as if sitting in a chair.',
      'Descend until your thighs are at least parallel to the floor.',
      'Drive through your heels to return to the starting position.',
    ],
    tips: ['Engage your core throughout the lift.', 'Ensure your knees track in line with your toes.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    emoji: '💪',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Legs', 'Glutes', 'Full Body'],
    workoutType: ['Strength', 'Powerlifting', 'Full Body'],
    description: 'A compound exercise that works multiple muscle groups, including the back, legs, and glutes. Involves lifting a barbell from the floor to a standing position.',
    instructions: [
      'Stand with your mid-foot under the barbell.',
      'Bend at your hips and knees, and grip the barbell with hands just outside your legs.',
      'Keep your back straight, chest up, and look forward.',
      'Lift the bar by extending your hips and knees, keeping the bar close to your body.',
      'Stand tall with shoulders back at the top.',
      'Lower the bar by reversing the motion, maintaining a flat back.',
    ],
    tips: ['Brace your core before lifting.', 'Do not round your lower back.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    emoji: '⬆️',
    muscleGroup: 'Shoulders',
    secondaryMuscleGroups: ['Triceps', 'Abs'],
    workoutType: ['Strength', 'Hypertrophy', 'Bodybuilding'],
    description: 'A compound exercise that targets the shoulders and triceps. Involves pressing a barbell or dumbbells overhead from a standing or seated position.',
    instructions: [
      'Stand with the barbell at shoulder height, hands slightly wider than shoulder-width.',
      'Engage your core and glutes.',
      'Press the bar straight overhead until your arms are fully extended.',
      'Lower the bar back to shoulder height in a controlled manner.',
    ],
    tips: ['Avoid flaring your elbows out too much.', 'Keep your core tight to prevent arching your back excessively.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'pull-up',
    name: 'Pull-up',
    emoji: '🤸',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Biceps', 'Shoulders'],
    workoutType: ['Strength', 'Bodybuilding', 'Calisthenics'],
    description: 'A bodyweight exercise that targets the upper back and biceps. Involves pulling your body up until your chin is over a bar.',
    instructions: [
      'Grip the pull-up bar with an overhand grip, hands slightly wider than shoulder-width.',
      'Hang with your arms fully extended.',
      'Pull your body up by squeezing your shoulder blades together and engaging your lats.',
      'Continue until your chin is over the bar.',
      'Lower your body slowly back to the starting position.',
    ],
    tips: ['Avoid using momentum (kipping) unless specifically training for it.', 'Full range of motion is key.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'running',
    name: 'Running',
    emoji: '🏃',
    muscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Legs'],
    workoutType: ['Cardio', 'Endurance'],
    description: 'A popular form of aerobic exercise. Can be done outdoors or on a treadmill.',
    instructions: [
      'Maintain an upright posture.',
      'Land midfoot to reduce impact.',
      'Keep a consistent pace suitable for your fitness level.',
    ],
    tips: ['Proper running shoes are important.', 'Stay hydrated.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'plank',
    name: 'Plank',
    emoji: '🧍',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Full Body'],
    workoutType: ['Strength', 'Core'],
    description: 'An isometric core strength exercise that involves maintaining a position similar to a push-up for the maximum possible time.',
    instructions: [
      'Lie face down and place your forearms on the floor, elbows directly under your shoulders.',
      'Lift your hips off the floor, creating a straight line from your head to your heels.',
      'Engage your core and glutes.',
      'Hold the position for the desired amount of time.',
    ],
    tips: ["Don't let your hips sag or rise too high.", 'Breathe steadily.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'superband-shoulder-rotation',
    name: 'Rotação de Ombros com Superband',
    emoji: '🔄',
    muscleGroup: 'Shoulders',
    workoutType: ['Warm-up', 'Flexibility', 'Mobilidade'],
    description: 'Aquecimento para os ombros utilizando uma superband para rotação, melhorando a mobilidade articular.',
    instructions: ['Segure a banda com as mãos afastadas, palmas para baixo.', 'Mantendo os braços esticados ou levemente flexionados, eleve a banda acima da cabeça e para trás, o mais longe que conseguir sem dor.', 'Retorne o movimento pela frente.', 'Gire os ombros para trás e para frente, mantendo os braços esticados ou levemente flexionados.'],
    tips: ['Mantenha o movimento controlado.', 'Erro: Arquear as costas excessivamente.', 'Regra: Imagine que está virando uma maçaneta gigante!'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'incline-push-up',
    name: 'Flexão Inclinada',
    emoji: '💪',
    muscleGroup: 'Chest',
    secondaryMuscleGroups: ['Shoulders', 'Triceps'],
    workoutType: ['Warm-up', 'Strength'],
    description: 'Uma variação mais fácil da flexão tradicional, realizada com as mãos em uma superfície elevada, ideal para iniciantes ou aquecimento.',
    instructions: ['Posicione as mãos em uma superfície elevada (banco, parede, caixa), um pouco mais largas que os ombros.', 'Mantenha o corpo reto da cabeça aos calcanhares, core ativado.', 'Desça o peito em direção à superfície dobrando os cotovelos.', 'Empurre de volta à posição inicial, estendendo os braços.'],
    tips: ['Mantenha o core ativado.', 'Controle a descida e a subida.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'ring-push-up',
    name: 'Flexão nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Chest',
    secondaryMuscleGroups: ['Shoulders', 'Triceps', 'Abs'],
    workoutType: ['Strength', 'Hypertrophy', 'Calisthenics'],
    description: 'Flexão realizada com as mãos em argolas de ginástica, aumentando a instabilidade e o recrutamento muscular do peito, ombros e tríceps.',
    instructions: [
        'Apoie as mãos nas argolas na altura do peito.',
        'Corpo reto, cotovelos a 45 graus.',
        'Desça até o peito alinhar com as mãos.',
        'Suba explosivamente.'
    ],
    tips: [
        'Mantenha o core ativado para estabilizar o corpo.',
        'Ajuste a altura das argolas para modificar a dificuldade.',
        'Erro: Quadris caídos ou o corpo balançar excessivamente.',
        'Regra: Core = cinto de segurança do movimento!',
        'Hack: Contraia glúteos.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'kettlebell-clean-press',
    name: 'Kettlebell Clean & Press',
    emoji: '🏋️',
    muscleGroup: 'Full Body',
    secondaryMuscleGroups: ['Shoulders', 'Legs', 'Triceps', 'Core'],
    workoutType: ['Strength', 'Powerlifting', 'Full Body', 'CrossFit'],
    description: 'Exercício composto que trabalha força e potência, movendo o kettlebell do chão para o ombro (clean) e depois empurrando-o acima da cabeça (press).',
    instructions: [
        'Posicione o kettlebell entre os pés.',
        'Faça um swing com o quadril para trás e puxe o KB do chão, guiando-o para a posição de rack no ombro (clean). O cotovelo deve ficar próximo ao corpo.',
        'Do ombro, estabilize e empurre o kettlebell para cima até o braço esticar completamente.',
        'Retorne o kettlebell ao ombro com controle e depois ao chão (ou para o próximo clean).',
        'Repita para o número desejado de repetições e depois troque o lado.'
    ],
    tips: [
        'Mantenha o core firme durante todo o movimento.',
        'Use as pernas e o quadril para gerar força no clean.',
        'Erro: Girar o pulso na subida do clean ou deixar o KB bater no antebraço.',
        'Regra (Clean): Cotovelo grudado no corpo na fase de puxar!'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'kettlebell-press',
    name: 'Kettlebell Press',
    emoji: '🏋️',
    muscleGroup: 'Shoulders',
    secondaryMuscleGroups: ['Triceps', 'Core'],
    workoutType: ['Strength', 'Hypertrophy'],
    description: 'Exercício para desenvolvimento de força e massa muscular nos ombros e tríceps, pressionando um kettlebell acima da cabeça a partir da posição de rack (ombro).',
    instructions: [
      'Segure o kettlebell na posição de rack no ombro (KB no ombro).',
      'Empurre para cima até o braço esticar.',
      'Volte com controle.',
      'Mantenha o core ativado e os pés firmes no chão.'
    ],
    tips: [
      'Mantenha o punho reto e alinhado com o antebraço.',
      'Erro: Arquear as costas.',
      'Hack: Expire ao empurrar.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kettlebell shoulder',
    isCustom: false,
  },
  {
    id: 'ring-dip',
    name: 'Mergulho nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Shoulders'],
    workoutType: ['Strength', 'Hypertrophy', 'Calisthenics'],
    description: 'Exercício desafiador para o tríceps, peito e ombros, utilizando argolas de ginástica para instabilidade.',
    instructions: ['Comece com os braços esticados, segurando as argolas, corpo suspenso e estável.', 'Mantenha as argolas próximas ao corpo.', 'Desça lentamente dobrando os cotovelos, até que os ombros cheguem aproximadamente na altura das mãos ou cotovelos formem um ângulo de 90 graus.', 'Empurre de volta à posição inicial, estendendo completamente os braços.'],
    tips: ['Mantenha o core ativado para evitar balanços.', 'Evite que os ombros rolem para frente; mantenha o peito aberto.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'superband-triceps-pushdown',
    name: 'Tríceps na Superband',
    emoji: '💪',
    muscleGroup: 'Triceps',
    workoutType: ['Strength', 'Hypertrophy', 'Warm-up'],
    description: 'Exercício de isolamento para o tríceps utilizando uma superband fixada em um ponto alto, focando na extensão do cotovelo.',
    instructions: ['Fixe a superband em um ponto alto e seguro (ex: barra de pull-up).', 'Segure as extremidades da banda com as duas mãos, palmas para baixo ou neutras, cotovelos próximos ao corpo.', 'Comece com os antebraços paralelos ao chão ou levemente acima.', 'Empurre a banda para baixo até que os braços estejam totalmente estendidos.', 'Retorne lentamente à posição inicial, controlando a tensão da banda.'],
    tips: ['Mantenha os cotovelos fixos ao lado do corpo, evitando que se abram.', 'Concentre-se na contração do tríceps no final do movimento.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'bodyweight-squat',
    name: 'Agachamento Livre',
    emoji: '🦵',
    muscleGroup: 'Legs',
    secondaryMuscleGroups: ['Glutes', 'Core'],
    workoutType: ['Warm-up', 'Strength', 'Calisthenics', 'Mobilidade'],
    description: 'Agachamento utilizando apenas o peso do corpo, fundamental para aquecimento, treino de pernas e desenvolvimento de padrão de movimento.',
    instructions: ['Fique em pé com os pés na largura dos ombros, pontas dos pés levemente para fora.', 'Mantenha o peito erguido, costas retas e o core ativado.', 'Agache como se fosse sentar em uma cadeira, levando o quadril para trás e para baixo, até que as coxas fiquem paralelas ao chão ou mais baixo, se possível.', 'Mantenha os calcanhares no chão.', 'Empurre com os calcanhares para voltar à posição inicial.'],
    tips: ['Mantenha os joelhos alinhados com os pés, não deixe que entrem.', 'Costas retas durante todo o movimento.', 'A profundidade é importante para ativação dos glúteos.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'dead-bug',
    name: 'Cachorro Morto (Dead Bug)',
    emoji: '🐞',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Core'],
    workoutType: ['Core', 'Warm-up', 'Flexibility', 'Mobilidade'],
    description: 'Exercício de core que melhora a estabilidade lombar e coordenação, mantendo a lombar pressionada contra o chão enquanto membros opostos se movem.',
    instructions: ['Deite-se de costas com os joelhos dobrados a 90 graus (acima do quadril) e os braços estendidos em direção ao teto (acima dos ombros).', 'Mantenha a lombar pressionada firmemente contra o chão (core ativado).', 'Estenda lentamente um braço para trás da cabeça (em direção ao chão) e a perna oposta em direção ao chão, sem tocar.', 'Retorne à posição inicial de forma controlada e repita com o outro lado (braço e perna opostos).'],
    tips: ['Mantenha o core sempre contraído para evitar que a lombar arqueie.', 'Movimentos lentos e controlados são mais eficazes.', 'Se sentir a lombar arquear, reduza a amplitude do movimento.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'kettlebell-goblet-squat',
    name: 'Agachamento Goblet (KB)',
    emoji: '🏋️',
    muscleGroup: 'Legs',
    secondaryMuscleGroups: ['Glutes', 'Abs', 'Core'],
    workoutType: ['Strength', 'Hypertrophy', 'Full Body'],
    description: 'Variação do agachamento onde um kettlebell é segurado na frente do peito, ajudando a manter o tronco ereto e engajando o core.',
    instructions: [
        'Segure o KB no peito.',
        'Agache até as coxas ficarem paralelas ao chão.',
        'Suba pelos calcanhares.',
        'Mantenha os pés na largura dos ombros ou um pouco mais afastados, pontas para fora.'
    ],
    tips: [
        'Mantenha o kettlebell próximo ao corpo.',
        'A profundidade é importante; tente quebrar a paralela se sua mobilidade permitir.',
        'Erro: Joelhos para dentro ou tronco caindo para frente.',
        'Regra: Empurre o chão com os calcanhares!',
        'Hack: Cotovelos contra coxas (para afastá-las na parte inferior do agachamento).'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'single-leg-hip-thrust',
    name: 'Ponte Glútea (1 perna)',
    emoji: '🦵',
    muscleGroup: 'Glutes',
    secondaryMuscleGroups: ['Hamstrings', 'Core'],
    workoutType: ['Strength', 'Hypertrophy', 'Calisthenics'],
    description: 'Exercício unilateral para glúteos, realizado deitado, elevando o quadril com apoio em uma perna e o pé da outra perna fora do chão.',
    instructions: [
        'Deitado, eleve o quadril com uma perna esticada.',
        'Segure 2 segundos no topo.',
        'Desça controladamente e repita. Troque de perna após as repetições.'
    ],
    tips: [
        'Concentre-se em usar o glúteo para levantar o quadril, não a lombar.',
        'Mantenha o core ativado para estabilizar.',
        'Erro: Deixar o quadril descer ou rodar.',
        'Regra: Contraia glúteos como se estivesse segurando uma nota de R$100!'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'ab-wheel-rollout-kneeling',
    name: 'Rollout com Rodinha (Ajoelhado)',
    emoji: '⚙️',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Shoulders', 'Back', 'Core', 'Full Body'],
    workoutType: ['Strength', 'Core'],
    description: 'Exercício intenso para o core utilizando a rodinha abdominal, partindo da posição ajoelhada. Fortalece e desafia toda a musculatura anterior do tronco.',
    instructions: [
        'Ajoelhado, segure a rodinha.',
        'Role para frente até quase tocar o chão com o peito.',
        'Volte com controle.',
        'Mantenha o core fortemente contraído.'
    ],
    tips: [
        'Não deixe a lombar cair, isso é um convite para dor nas costas.',
        'Comece com uma amplitude menor e aumente conforme ganha força.',
        'Erro: Arquear a lombar.',
        'Regra: Abdômen mais duro que a realidade!',
        'Hack: Mantenha o nariz alinhado com o umbigo durante o movimento para ajudar a manter a coluna neutra.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'dynamic-plank-shoulder-taps',
    name: 'Prancha Dinâmica (Toque no Ombro)',
    emoji: '🧍‍♂️',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Shoulders', 'Full Body', 'Core', 'Triceps'],
    workoutType: ['Core', 'Strength', 'Warm-up'],
    description: 'Variação da prancha tradicional onde se alterna o toque da mão no ombro oposto, aumentando o desafio de estabilização anti-rotacional do core.',
    instructions: ['Comece na posição de prancha alta (mãos diretamente abaixo dos ombros, corpo reto dos calcanhares à cabeça).', 'Mantenha o quadril estável e evite balançar o corpo lateralmente.', 'Lentamente, levante uma mão do chão e toque o ombro oposto.', 'Retorne a mão ao chão de forma controlada e repita com o outro lado.', 'Alterne continuamente durante o tempo determinado.'],
    tips: ['Quanto mais lento o movimento, maior o desafio para o core.', 'Afaste os pés para maior estabilidade, se necessário.', 'Concentre-se em manter o umbigo apontado para o chão.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'jumping-jacks',
    name: 'Polichinelos',
    emoji: '🤸‍♀️',
    muscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Full Body', 'Legs', 'Shoulders'],
    workoutType: ['Cardio', 'Warm-up', 'HIIT'],
    description: 'Exercício cardiovascular clássico que envolve saltar para uma posição com as pernas abertas e as mãos se tocando (ou quase) acima da cabeça.',
    instructions: ['Comece em pé com os pés juntos e os braços ao lado do corpo.', 'Em um movimento coordenado, salte abrindo as pernas para além da largura dos ombros enquanto eleva os braços lateralmente até que as mãos se encontrem (ou cheguem perto) acima da cabeça.', 'Salte novamente, retornando os pés à posição inicial e os braços ao lado do corpo.', 'Repita em um ritmo constante.'],
    tips: ['Mantenha um ritmo que consiga sustentar.', 'Aterrisse suavemente na ponta dos pés.', 'Pode ser usado como aquecimento ou parte de um treino HIIT.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'burpees',
    name: 'Burpees',
    emoji: '🥵',
    muscleGroup: 'Full Body',
    secondaryMuscleGroups: ['Cardio', 'Legs', 'Chest', 'Shoulders', 'Abs'],
    workoutType: ['Cardio', 'Strength', 'HIIT', 'CrossFit'],
    description: 'Exercício de corpo inteiro altamente intenso que combina agachamento, prancha, flexão (opcional) e salto vertical.',
    instructions: [
        'Agache, jogue os pés para trás.',
        'Faça uma flexão.',
        'Salte para cima.',
        'Comece em pé.',
        'Aterrisse suavemente e repita.'
    ],
    tips: [
        'Mantenha um ritmo que consiga sustentar, mas desafiador.',
        'Pode ser modificado removendo a flexão ou o salto vertical para iniciantes.',
        'Erro: Joelhos valgos (para dentro) no salto.',
        'Regra: Velocidade > perfeição! (neste caso, para o HIIT)'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'ab-wheel-mobility-abdominal',
    name: 'Mobilidade Abdominal com Rodinha',
    emoji: '⚙️',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Flexibility', 'Core'],
    workoutType: ['Flexibility', 'Mobilidade', 'Cooldown'],
    description: 'Uso da rodinha abdominal para massagem suave e liberação miofascial da região abdominal, promovendo mobilidade.',
    instructions: ['Deite-se de bruços ou fique de quatro.', 'Posicione a rodinha abdominal sob o seu abdômen.', 'Role lentamente a rodinha para cima e para baixo e de um lado para o outro sobre a região abdominal, aplicando uma pressão suave e controlada.', 'Concentre-se em áreas de tensão, respirando profundamente.'],
    tips: ['Seja gentil, especialmente no início; evite pressão excessiva.', 'Evite rolar sobre ossos (costelas, quadril) ou áreas muito sensíveis.', 'Este não é um exercício de fortalecimento, mas de mobilidade e liberação.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'superband-inverted-row',
    name: 'Remada invertida com Superband',
    emoji: '💪',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Biceps', 'Shoulders'],
    workoutType: ['Strength', 'Warm-up', 'Calisthenics'],
    description: 'Variação da remada invertida utilizando uma superband para ajustar a dificuldade ou como ponto de ancoragem em uma barra baixa.',
    instructions: ['Fixe uma superband em um suporte baixo e estável (ex: poste, rack), ou passe-a por uma barra baixa.', 'Segure a banda (ou a barra com a banda auxiliando) com as mãos na largura dos ombros, palmas para baixo ou para cima.', 'Posicione o corpo inclinado para trás, com os calcanhares no chão e o corpo reto dos tornozelos à cabeça.', 'Puxe o peito em direção ao ponto de ancoragem (ou à barra), contraindo as omoplatas.', 'Desça controladamente até os braços estarem quase esticados.'],
    tips: ['Quanto mais horizontal o corpo, mais difícil o exercício.', 'Mantenha o core firme para evitar que o quadril caia.', 'Concentre-se em puxar com os músculos das costas.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'cat-cow-stretch',
    name: 'Alongamento Gato-Vaca',
    emoji: '🧘',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Abs', 'Core'],
    workoutType: ['Flexibility', 'Warm-up', 'Yoga', 'Mobilidade'],
    description: 'Movimento de yoga que alonga e aquece a coluna vertebral, promovendo mobilidade e aliviando tensões.',
    instructions: ['Comece na posição de quatro apoios (mãos diretamente abaixo dos ombros, joelhos diretamente abaixo do quadril).', 'Inspire, arqueando as costas para baixo (extensão da coluna), elevando a cabeça e o cóccix em direção ao teto (postura da vaca).', 'Expire, arredondando as costas para cima (flexão da coluna), levando o queixo ao peito e o cóccix para baixo (postura do gato).', 'Alterne entre as duas posturas de forma fluida, sincronizando com a respiração.'],
    tips: ['Mantenha os movimentos lentos e controlados.', 'Concentre-se na mobilidade de cada vértebra.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'ring-pull-up',
    name: 'Pull-Up nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Biceps', 'Shoulders', 'Abs', 'Core'],
    workoutType: ['Strength', 'Hypertrophy', 'Calisthenics'],
    description: 'Pull-up (barra fixa) realizado em argolas, permitindo um movimento mais natural das articulações do punho e ombro, e maior recrutamento de estabilizadores.',
    instructions: [
        'Segure as argolas com as palmas para você.',
        'Puxe até o queixo passar das mãos.',
        'Comece com os braços totalmente esticados (posição de pendurado).',
        'Desça de forma controlada até a extensão total dos braços.'
    ],
    tips: [
        'Mantenha o core ativado para evitar balanços excessivos.',
        'Erro: Balançar as pernas para ganhar impulso.',
        'Regra: Ative as costas, não só os braços!',
        'Hack: Ombros para trás.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'kettlebell-bent-over-row',
    name: 'Remada Curvada (KB)',
    emoji: '🏋️',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Biceps', 'Shoulders', 'Core'],
    workoutType: ['Strength', 'Hypertrophy'],
    description: 'Exercício para as costas (principalmente dorsais e romboides) utilizando um ou dois kettlebells, realizado com o tronco inclinado à frente.',
    instructions: [
        'Segure um kettlebell em cada mão (ou um único KB com as duas mãos).',
        'Incline o tronco para frente a partir do quadril, mantendo as costas retas (aproximadamente paralelo ao chão). Joelhos levemente flexionados.',
        'Deixe os braços esticados em direção ao chão.',
        'Puxe o(s) KB(s) em direção à parte inferior do peito ou costelas, contraindo as omoplatas.',
        'Desça os kettlebells de forma controlada de volta à posição inicial.'
    ],
    tips: [
        'Mantenha o core firme e as costas retas para proteger a lombar.',
        'Concentre-se em usar os músculos das costas para puxar, não apenas os braços.',
        'Erro: Rotacionar o tronco ou usar impulso para levantar o peso. Curvar a lombar.',
        'Regra: Cotovelo deve \'raspar\' no corpo (ou passar próximo a ele)!'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'superband-face-pull',
    name: 'Face Pull com Superband',
    emoji: '💪',
    muscleGroup: 'Shoulders',
    secondaryMuscleGroups: ['Back', 'Triceps'],
    workoutType: ['Hypertrophy', 'Strength', 'Corrective', 'Warm-up'],
    description: 'Exercício excelente para a saúde dos ombros, fortalecimento do manguito rotador, trapézios mediais/inferiores e deltoides posteriores, usando uma superband.',
    instructions: ['Fixe uma superband em um ponto de ancoragem na altura do peito ou rosto.', 'Segure as extremidades da banda com as duas mãos, palmas para baixo ou neutras (polegares para cima).', 'Afaste-se para criar tensão na banda.', 'Puxe a banda em direção ao seu rosto (nariz/testa), mantendo os cotovelos altos e para fora (mais altos que os punhos).', 'Conduza o movimento com os cotovelos, apertando as omoplatas juntas na parte de trás do movimento.', 'Retorne lentamente à posição inicial, controlando a tensão.'],
    tips: ['Concentre-se na rotação externa dos ombros e na retração das escápulas.', 'Não use impulso; o movimento deve ser controlado.', 'Mantenha os ombros para baixo, longe das orelhas.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'ab-wheel-rollout-standing',
    name: 'Rollout em Pé (Avançado)',
    emoji: '⚙️',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Full Body', 'Core', 'Shoulders', 'Back'],
    workoutType: ['Strength', 'Core', 'Advanced', 'Calisthenics'],
    description: 'Variação extremamente avançada do rollout com rodinha, realizada a partir da posição em pé. Requer grande força, controle e estabilidade do core.',
    instructions: [
        'De pé, role a rodinha para frente.',
        'Mantenha o corpo reto.',
        'Fique em pé com os pés na largura dos ombros, segurando a rodinha abdominal.',
        'Incline-se para frente a partir do quadril, colocando a rodinha no chão à sua frente.',
        'Use a força do core para reverter o movimento e rolar a rodinha de volta até ficar em pé novamente.'
    ],
    tips: [
        'Este é um exercício muito avançado. Domine completamente o rollout ajoelhado antes de tentar.',
        'Comece com uma amplitude muito pequena e aumente gradualmente ao longo de semanas ou meses.',
        'Erro: Deixar a lombar cair ou perder a tensão do core. Usar impulso excessivo.',
        'Regra: Abdômen contraído = escudo contra lesões! Se sentir qualquer desconforto na lombar, pare.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'ring-plank',
    name: 'Prancha nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Shoulders', 'Full Body', 'Core', 'Triceps'],
    workoutType: ['Core', 'Strength', 'Calisthenics', 'Isometric'],
    description: 'Posição de prancha mantida com as mãos ou antebraços em argolas, aumentando significativamente o desafio de estabilização devido à instabilidade das argolas.',
    instructions: [
        'Apoie os antebraços nas argolas.',
        'Mantenha o corpo alinhado.',
        'Ajuste as argolas a uma altura baixa, próxima ao chão.',
        'Estenda as pernas para trás, formando uma linha reta dos calcanhares à cabeça.',
        'Contraia o core e os glúteos para manter a estabilidade.',
        'Sustente a posição pelo tempo desejado.'
    ],
    tips: [
        'Concentre-se em manter as argolas paradas e o corpo estável.',
        'Respire normalmente durante a execução.',
        'Erro: Quadris muito altos ou muito baixos (arqueando a lombar). Deixar as argolas se moverem descontroladamente.',
        'Regra: Imagine uma linha reta dos tornozelos à cabeça! Mantenha tudo contraído.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'kettlebell-russian-twist',
    name: 'Russian Twist (KB)',
    emoji: '🔄',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Obliques', 'Core'],
    workoutType: ['Core', 'Strength'],
    description: 'Exercício para os oblíquos e core, realizado sentado com o tronco inclinado para trás, torcendo o torso de um lado para o outro segurando um kettlebell.',
    instructions: ['Sente-se no chão com os joelhos dobrados e os pés levemente levantados do chão (ou apoiados para facilitar).', 'Incline o tronco para trás em cerca de 45 graus, mantendo as costas retas e o core ativado.', 'Segure um kettlebell com as duas mãos na frente do peito.', 'Torça o tronco lentamente para um lado, levando o kettlebell em direção ao chão ao lado do quadril.', 'Retorne ao centro e torça para o outro lado.', 'Continue alternando os lados de forma controlada.'],
    tips: ['Mantenha o movimento controlado, focando na contração dos oblíquos.', 'Evite usar impulso com os braços; o movimento deve vir do tronco.', 'Mantenha a cabeça e o peito erguidos.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'chest-release-wheel',
    name: 'Liberação de Peitoral (Rodinha)',
    emoji: '🧘',
    muscleGroup: 'Chest',
    secondaryMuscleGroups: ['Shoulders'],
    workoutType: ['Flexibility', 'Mobilidade', 'Cooldown'],
    description: 'Liberação miofascial para o peitoral utilizando a rodinha abdominal para aliviar tensões e melhorar a mobilidade.',
    instructions: ["Deite-se de bruços ou de lado.", "Posicione a rodinha abdominal sob uma das laterais do seu peito.", "Use o peso do corpo para aplicar pressão e role lentamente sobre a área do peitoral.", "Concentre-se em áreas de maior tensão, respirando profundamente."],
    tips: ["Erro: Pressão excessiva ou rolar sobre áreas ósseas.", "Regra: Respire e solte a tensão. Seja gentil, especialmente no início."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'chest mobility',
    isCustom: false,
  },
  {
    id: 'hamstring-stretch-seated',
    name: 'Alongamento de Isquiotibiais (Sentado)',
    emoji: '🧘',
    muscleGroup: 'Hamstrings',
    secondaryMuscleGroups: ['Legs', 'Back'],
    workoutType: ['Flexibility', 'Cooldown'],
    description: 'Alongamento para os músculos isquiotibiais (posteriores da coxa), realizado sentado, que ajuda a melhorar a flexibilidade e aliviar tensões.',
    instructions: ["Sente-se no chão com as pernas esticadas à sua frente.", "Mantenha as costas retas e incline o tronco para frente a partir do quadril, tentando alcançar os pés com as mãos.", "Mantenha o alongamento por 20-30 segundos, respirando profundamente."],
    tips: ["Erro: Forçar a coluna (curvar as costas) para alcançar mais longe. Mantenha os joelhos levemente flexionados se necessário.", "Regra: Mantenha a respiração calma e constante. Sinta o alongamento na parte de trás das coxas."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'hamstring stretch',
    isCustom: false,
  },
  {
    id: 'hip-mobility-wheel',
    name: 'Mobilidade de Quadril (Rodinha)',
    emoji: '🧘',
    muscleGroup: 'Hips',
    secondaryMuscleGroups: ['Glutes'],
    workoutType: ['Flexibility', 'Mobilidade', 'Warm-up'],
    description: 'Liberação miofascial para os glúteos e quadril utilizando a rodinha abdominal, ajudando a soltar tensões e melhorar a mobilidade da região.',
    instructions: ["Sente-se sobre a rodinha abdominal, posicionando-a sob um dos glúteos.", "Apoie-se com as mãos atrás de você e, se desejar, cruze o tornozelo do lado que está sendo trabalhado sobre o joelho oposto.", "Role lentamente sobre a área do glúteo, procurando pontos de tensão.", "Mantenha a pressão sobre os pontos tensos por alguns segundos, respirando profundamente."],
    tips: ["Erro: Pressão em áreas ósseas ou rolar muito rapidamente.", "Regra: Use o peso do corpo para controlar a pressão e liberar a tensão. Seja paciente."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'hip mobility',
    isCustom: false,
  },
  {
    id: 'jump-squat',
    name: 'Agachamento com Salto',
    emoji: '🤸‍♀️',
    muscleGroup: 'Legs',
    secondaryMuscleGroups: ['Glutes', 'Cardio', 'Core'],
    workoutType: ['Plyometrics', 'Strength', 'Cardio', 'HIIT'],
    description: 'Agachamento explosivo seguido de um salto vertical para desenvolver potência nas pernas e aumentar a frequência cardíaca.',
    instructions: ["Agache até 90 graus.", "Salte o mais alto possível.", "Comece em pé, pés na largura dos ombros.", "Aterrisse suavemente, absorvendo o impacto com os joelhos flexionados, e prepare-se para o próximo salto."],
    tips: ["Erro: Aterrissar com os joelhos travados ou deixar os joelhos desalinharem.", "Regra: Aterrisse como um gato, não como um elefante! (Suavemente, absorvendo o impacto).", "Mantenha o core ativado durante todo o movimento."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'jump squat',
    isCustom: false,
  },
  {
    id: 'jump-rope',
    name: 'Pular Corda',
    emoji: '🤸‍♀️',
    muscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Legs', 'Full Body'],
    workoutType: ['Cardio', 'Warm-up', 'HIIT', 'Endurance'],
    description: 'Exercício cardiorrespiratório eficaz que melhora a coordenação, agilidade e resistência. Pode ser de baixa ou alta intensidade.',
    instructions: [
      'Segure as manoplas da corda, uma em cada mão, com os cotovelos próximos ao corpo.',
      'Use os pulsos e antebraços para girar a corda, não os ombros.',
      'Salte baixo, apenas o suficiente para a corda passar sob os pés. Mantenha os joelhos levemente flexionados.',
      'Aterrisse suavemente na ponta dos pés.'
    ],
    tips: [
      'Mantenha um ritmo constante e a respiração controlada.',
      'Comece com saltos básicos e progrida para variações (ex: alternando os pés, joelhos altos) conforme ganha confiança.',
      'Ajuste o comprimento da corda: pisando no meio da corda, as manoplas devem alcançar suas axilas.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'jump rope',
    isCustom: false,
  },
  {
    id: 'superband-jumps',
    name: 'Saltos com Superband',
    emoji: '🤸‍♂️',
    muscleGroup: 'Legs',
    secondaryMuscleGroups: ['Cardio', 'Glutes', 'Core'],
    workoutType: ['Plyometrics', 'HIIT', 'Strength'],
    description: 'Saltos explosivos (verticais, horizontais, etc.) realizados contra a resistência de uma superband para aumentar a potência e a força das pernas.',
    instructions: [
      'Ancore a superband em um ponto fixo e seguro (baixo para saltos verticais/horizontais com a banda na cintura) ou peça para um parceiro segurar a outra extremidade.',
      'Posicione a banda ao redor da sua cintura ou segure-a, dependendo do tipo de salto.',
      'Realize saltos explosivos (para cima, para frente, laterais) contra a resistência da banda.',
      'Concentre-se na máxima explosão em cada salto.'
    ],
    tips: [
      'Aterrisse suavemente, absorvendo o impacto.',
      'Mantenha o core ativado para estabilidade.',
      'Ajuste a tensão da banda para o nível de dificuldade desejado.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'band jumps',
    isCustom: false,
  },
  {
    id: 'diamond-push-up',
    name: 'Flexão Diamante',
    emoji: '💎',
    muscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Shoulders', 'Core'],
    workoutType: ['Strength', 'Hypertrophy', 'Calisthenics'],
    description: 'Uma variação desafiadora da flexão que foca intensamente nos tríceps, com as mãos posicionadas próximas no chão, formando um diamante com os polegares e indicadores.',
    instructions: [
      'Posicione as mãos no chão diretamente sob o peito, com os dedos indicadores e polegares se tocando para formar um formato de diamante.',
      'Estenda as pernas para trás, entrando na posição de prancha alta, corpo reto dos calcanhares à cabeça.',
      'Baixe o corpo dobrando os cotovelos, mantendo-os próximos ao corpo, até que o peito quase toque as mãos.',
      'Empurre de volta à posição inicial, estendendo completamente os braços e focando na contração do tríceps.'
    ],
    tips: [
      'Mantenha o core ativado durante todo o movimento para evitar que o quadril caia.',
      'Se for muito difícil, comece com os joelhos no chão ou realize flexões inclinadas com as mãos em diamante.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'triceps pushup',
    isCustom: false,
  },
  {
    id: 'plank-rotation',
    name: 'Prancha com Rotação',
    emoji: '🔄',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Obliques', 'Shoulders', 'Core'],
    workoutType: ['Core', 'Strength', 'Mobilidade'],
    description: 'Exercício de prancha lateral dinâmica que envolve rotação do tronco, engajando fortemente os oblíquos e melhorando a estabilidade e mobilidade do core.',
    instructions: [
      'Comece em posição de prancha lateral, apoiado no antebraço direito e na lateral do pé direito. O corpo deve formar uma linha reta.',
      'Estenda o braço esquerdo em direção ao teto.',
      'Lentamente, rotacione o tronco levando o braço esquerdo por baixo do corpo, em direção ao espaço entre o seu corpo e o chão.',
      'Reverta o movimento, retornando o braço esquerdo para o teto.',
      'Controle o movimento durante toda a amplitude.',
      'Repita pelo número desejado de repetições e depois troque de lado.'
    ],
    tips: [
      'Mantenha o quadril elevado e estável; não deixe que ele caia ou gire excessivamente.',
      'O movimento deve ser controlado e originado no core, não no braço.',
      'Mantenha o cotovelo de apoio diretamente abaixo do ombro.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'core rotation',
    isCustom: false,
  },
  {
    id: 'dynamic-stretching',
    name: 'Alongamento Dinâmico',
    emoji: '🧘‍♂️',
    muscleGroup: 'Full Body',
    workoutType: ['Warm-up', 'Flexibility', 'Mobilidade'],
    description: 'Sequência de movimentos fluidos e controlados que levam as articulações e músculos através de sua amplitude de movimento completa. Prepara o corpo para o exercício.',
    instructions: [
      'Realize movimentos como balanços de perna (frontais, laterais).',
      'Círculos com os braços (para frente, para trás, grandes e pequenos).',
      'Rotações de tronco (suaves e controladas).',
      'Agachamentos com peso corporal, afundos com alcance, etc.',
      'Mantenha os movimentos controlados e progressivos, aumentando gradualmente a amplitude.',
      'Concentre-se em aquecer as principais articulações e grupos musculares que serão trabalhados na sessão.'
    ],
    tips: [
      'Não force além da sua amplitude de movimento confortável, especialmente no início.',
      'Aumente a intensidade e a amplitude gradualmente.',
      'Respire normalmente durante os movimentos.',
      'Diferente do alongamento estático, não segure as posições por longos períodos.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'stretching dynamic',
    isCustom: false,
  },
];

