
import type { Exercise } from '@/types';

export const PRELOADED_EXERCISES: Exercise[] = [
  {
    id: 'bench-press',
    name: 'Bench Press',
    emoji: '🏋️',
    muscleGroup: 'Chest',
    secondaryMuscleGroups: ['Shoulders', 'Triceps'],
    workoutType: ['Strength', 'Hypertrophy', 'Powerlifting', 'Bodybuilding'],
    description: 'A compound exercise that targets the chest, shoulders, and triceps. Lie on a bench and lower a barbell to your chest, then press it back up.',
    instructions: [
      'Lie flat on a bench with your feet firmly on the ground.',
      'Grip the barbell with hands slightly wider than shoulder-width apart.',
      'Lower the bar slowly to your mid-chest, keeping your elbows tucked at about a 45-degree angle.',
      'Press the bar back up until your arms are fully extended, without locking your elbows.',
    ],
    tips: ['Keep your glutes on the bench and maintain a slight arch in your lower back.', 'Control the weight throughout the movement.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'squat',
    name: 'Barbell Squat',
    emoji: '🦵',
    muscleGroup: 'Legs',
    secondaryMuscleGroups: ['Glutes', 'Back'],
    workoutType: ['Strength', 'Hypertrophy', 'Powerlifting', 'Bodybuilding'],
    description: 'A fundamental compound exercise that primarily targets the quadriceps, hamstrings, and glutes. Involves squatting down with a barbell on your upper back.',
    instructions: [
      'Stand with your feet shoulder-width apart, toes pointing slightly outwards.',
      'Rest the barbell on your upper back (traps), not on your neck.',
      'Keeping your chest up and back straight, lower your hips as if sitting in a chair.',
      'Descend until your thighs are at least parallel to the floor.',
      'Drive through your heels to return to the starting position.',
    ],
    tips: ['Engage your core throughout the lift.', 'Ensure your knees track in line with your toes.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    emoji: '💪',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Legs', 'Glutes', 'Full Body'],
    workoutType: ['Strength', 'Powerlifting', 'Full Body'],
    description: 'A compound exercise that works multiple muscle groups, including the back, legs, and glutes. Involves lifting a barbell from the floor to a standing position.',
    instructions: [
      'Stand with your mid-foot under the barbell.',
      'Bend at your hips and knees, and grip the barbell with hands just outside your legs.',
      'Keep your back straight, chest up, and look forward.',
      'Lift the bar by extending your hips and knees, keeping the bar close to your body.',
      'Stand tall with shoulders back at the top.',
      'Lower the bar by reversing the motion, maintaining a flat back.',
    ],
    tips: ['Brace your core before lifting.', 'Do not round your lower back.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    emoji: '⬆️',
    muscleGroup: 'Shoulders',
    secondaryMuscleGroups: ['Triceps', 'Abs'],
    workoutType: ['Strength', 'Hypertrophy', 'Bodybuilding'],
    description: 'A compound exercise that targets the shoulders and triceps. Involves pressing a barbell or dumbbells overhead from a standing or seated position.',
    instructions: [
      'Stand with the barbell at shoulder height, hands slightly wider than shoulder-width.',
      'Engage your core and glutes.',
      'Press the bar straight overhead until your arms are fully extended.',
      'Lower the bar back to shoulder height in a controlled manner.',
    ],
    tips: ['Avoid flaring your elbows out too much.', 'Keep your core tight to prevent arching your back excessively.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'pull-up',
    name: 'Pull-up',
    emoji: '🤸',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Biceps', 'Shoulders'],
    workoutType: ['Strength', 'Bodybuilding', 'Calisthenics'],
    description: 'A bodyweight exercise that targets the upper back and biceps. Involves pulling your body up until your chin is over a bar.',
    instructions: [
      'Grip the pull-up bar with an overhand grip, hands slightly wider than shoulder-width.',
      'Hang with your arms fully extended.',
      'Pull your body up by squeezing your shoulder blades together and engaging your lats.',
      'Continue until your chin is over the bar.',
      'Lower your body slowly back to the starting position.',
    ],
    tips: ['Avoid using momentum (kipping) unless specifically training for it.', 'Full range of motion is key.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'running',
    name: 'Running',
    emoji: '🏃',
    muscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Legs'],
    workoutType: ['Cardio', 'Endurance'],
    description: 'A popular form of aerobic exercise. Can be done outdoors or on a treadmill.',
    instructions: [
      'Maintain an upright posture.',
      'Land midfoot to reduce impact.',
      'Keep a consistent pace suitable for your fitness level.',
    ],
    tips: ['Proper running shoes are important.', 'Stay hydrated.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'plank',
    name: 'Plank',
    emoji: '🧍',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Full Body'],
    workoutType: ['Strength', 'Core'],
    description: 'An isometric core strength exercise that involves maintaining a position similar to a push-up for the maximum possible time.',
    instructions: [
      'Lie face down and place your forearms on the floor, elbows directly under your shoulders.',
      'Lift your hips off the floor, creating a straight line from your head to your heels.',
      'Engage your core and glutes.',
      'Hold the position for the desired amount of time.',
    ],
    tips: ["Don't let your hips sag or rise too high.", 'Breathe steadily.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'superband-shoulder-rotation',
    name: 'Rotação de Ombros com Superband',
    emoji: '🔄',
    muscleGroup: 'Shoulders',
    workoutType: ['Warm-up', 'Flexibility'],
    description: 'Aquecimento para os ombros utilizando uma superband para rotação.',
    instructions: ['Segure a banda com as mãos afastadas.', 'Gire os ombros para trás e para frente, mantendo os braços esticados ou levemente flexionados.'],
    tips: ['Erro: Arquear as costas.', 'Regra: Imagine que está virando uma maçaneta gigante!', 'Mantenha o movimento controlado.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'incline-push-up',
    name: 'Flexão Inclinada',
    emoji: '💪',
    muscleGroup: 'Chest',
    secondaryMuscleGroups: ['Shoulders', 'Triceps'],
    workoutType: ['Warm-up', 'Strength'],
    description: 'Uma variação mais fácil da flexão tradicional, realizada com as mãos em uma superfície elevada.',
    instructions: ['Posicione as mãos em uma superfície elevada (banco, parede).', 'Mantenha o corpo reto da cabeça aos calcanhares.', 'Desça o peito em direção à superfície e empurre de volta.'],
    tips: ['Mantenha o core ativado.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'ring-push-up',
    name: 'Flexão nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Chest',
    secondaryMuscleGroups: ['Shoulders', 'Triceps', 'Abs'],
    workoutType: ['Strength', 'Hypertrophy', 'Calisthenics'],
    description: 'Flexão realizada com as mãos em argolas de ginástica, aumentando a instabilidade e o recrutamento muscular.',
    instructions: [
        'Apoie as mãos nas argolas.',
        'Desça até o peito chegar na altura das mãos.',
        'Suba explosivamente.'
    ],
    tips: [
        'Erro: Deixar os quadris caírem.',
        'Regra: Core = cinto de segurança do movimento!',
        'Mantenha o core ativado para estabilizar o corpo.', 
        'Ajuste a altura das argolas para modificar a dificuldade.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'kettlebell-clean-press',
    name: 'Kettlebell Clean & Press',
    emoji: '🏋️',
    muscleGroup: 'Full Body',
    secondaryMuscleGroups: ['Shoulders', 'Legs', 'Triceps'],
    workoutType: ['Strength', 'Powerlifting', 'Full Body'],
    description: 'Exercício composto que trabalha força e potência, movendo o kettlebell do chão para o ombro (clean) e depois empurrando-o acima da cabeça (press).',
    instructions: [
        'Puxe o KB do chão até o ombro.',
        'Empurre para cima até o braço esticar.',
        'Retorne o kettlebell ao ombro e depois ao chão de forma controlada.',
        'Repita para o número desejado de repetições e depois troque o lado.'
    ],
    tips: [
        'Erro: Girar o pulso na subida.',
        'Regra: Cotovelo grudado no corpo na fase de puxar!',
        'Mantenha o core firme durante todo o movimento.',
        'Use as pernas e o quadril para gerar força no clean.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'ring-dip',
    name: 'Mergulho nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Shoulders'],
    workoutType: ['Strength', 'Hypertrophy', 'Calisthenics'],
    description: 'Exercício desafiador para o tríceps, peito e ombros, utilizando argolas de ginástica.',
    instructions: ['Comece com os braços esticados, segurando as argolas, corpo suspenso.', 'Mantenha as argolas próximas ao corpo.', 'Desça lentamente até que os ombros cheguem aproximadamente na altura das mãos ou cotovelos formem 90 graus.', 'Empurre de volta à posição inicial, estendendo completamente os braços.'],
    tips: ['Mantenha o core ativado.', 'Evite que os ombros rolem para frente.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'superband-triceps-pushdown',
    name: 'Tríceps na Superband',
    emoji: '💪',
    muscleGroup: 'Triceps',
    workoutType: ['Strength', 'Hypertrophy'],
    description: 'Exercício de isolamento para o tríceps utilizando uma superband fixada em um ponto alto.',
    instructions: ['Fixe a superband em um ponto alto e seguro.', 'Segure as extremidades da banda com as duas mãos, cotovelos próximos ao corpo.', 'Empurre a banda para baixo até que os braços estejam totalmente estendidos.', 'Retorne lentamente à posição inicial, controlando a tensão da banda.'],
    tips: ['Mantenha os cotovelos fixos ao lado do corpo, evitando que se abram.', 'Concentre-se na contração do tríceps.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'bodyweight-squat',
    name: 'Agachamento Livre',
    emoji: '🦵',
    muscleGroup: 'Legs',
    secondaryMuscleGroups: ['Glutes'],
    workoutType: ['Warm-up', 'Strength', 'Calisthenics'],
    description: 'Agachamento utilizando apenas o peso do corpo, fundamental para aquecimento e treino de pernas.',
    instructions: ['Fique em pé com os pés na largura dos ombros.', 'Mantenha o peito erguido e o core ativado.', 'Agache como se fosse sentar em uma cadeira, até que as coxas fiquem paralelas ao chão ou mais baixo, se possível.', 'Empurre com os calcanhares para voltar à posição inicial.'],
    tips: ['Mantenha os joelhos alinhados com os pés, não deixe que entrem.', 'Costas retas durante todo o movimento.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'dead-bug',
    name: 'Cachorro Morto (Dead Bug)',
    emoji: '🐞',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Core'],
    workoutType: ['Core', 'Warm-up', 'Flexibility'],
    description: 'Exercício de core que melhora a estabilidade e coordenação, mantendo a lombar pressionada contra o chão.',
    instructions: ['Deite-se de costas com os joelhos dobrados a 90 graus e os braços estendidos em direção ao teto.', 'Mantenha a lombar pressionada contra o chão.', 'Estenda lentamente um braço para trás da cabeça e a perna oposta em direção ao chão.', 'Retorne à posição inicial e repita com o outro lado.'],
    tips: ['Mantenha o core sempre contraído.', 'Movimentos lentos e controlados são mais eficazes.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'kettlebell-goblet-squat',
    name: 'Agachamento Goblet (KB)',
    emoji: '🏋️',
    muscleGroup: 'Legs',
    secondaryMuscleGroups: ['Glutes', 'Abs'],
    workoutType: ['Strength', 'Hypertrophy'],
    description: 'Variação do agachamento onde um kettlebell é segurado na frente do peito.',
    instructions: [
        'Segure o KB no peito.',
        'Agache até as coxas ficarem paralelas ao chão.',
        'Empurre com os calcanhares para retornar à posição inicial.'
    ],
    tips: [
        'Erro: Joelhos para dentro.',
        'Regra: Empurre o chão com os calcanhares!',
        'Mantenha o kettlebell próximo ao corpo.',
        'A profundidade é importante; tente quebrar a paralela.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'single-leg-hip-thrust',
    name: 'Ponte Glútea (1 perna)', // Updated name based on user plan
    emoji: '🦵',
    muscleGroup: 'Glutes',
    secondaryMuscleGroups: ['Hamstrings'],
    workoutType: ['Strength', 'Hypertrophy'],
    description: 'Exercício unilateral para glúteos, realizado deitado, elevando o quadril com apoio em uma perna.',
    instructions: [
        'Deitado, eleve o quadril com uma perna esticada.',
        'Segure 2s no topo.',
        'Desça controladamente e repita. Troque de perna após as repetições.'
    ],
    tips: [
        'Erro: Deixar o quadril descer.',
        'Regra: Contraia glúteos como se estivesse segurando uma nota de R$100!',
        'Concentre-se em usar o glúteo para levantar o quadril, não a lombar.',
        'Mantenha o core ativado.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'ab-wheel-rollout-kneeling',
    name: 'Rollout com Rodinha (Ajoelhado)',
    emoji: '⚙️',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Shoulders', 'Back', 'Core'],
    workoutType: ['Strength', 'Core'],
    description: 'Exercício intenso para o core utilizando a rodinha abdominal, partindo da posição ajoelhada.',
    instructions: [
        'Ajoelhado, segure a rodinha.',
        'Role para frente até quase tocar o chão com o peito.',
        'Volte com controle.'
    ],
    tips: [
        'Erro: Arquear a lombar.',
        'Regra: Abdômen mais duro que a realidade!',
        'Mantenha o core TÃO TENSIONADO quanto sua cara ao ver o preço do açaí.',
        'Não deixe a lombar cair, isso é um convite para dor nas costas.',
        'Comece com uma amplitude menor e aumente conforme ganha força.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'dynamic-plank-shoulder-taps',
    name: 'Prancha Dinâmica (Toque no Ombro)',
    emoji: '🧍‍♂️',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Shoulders', 'Full Body', 'Core'],
    workoutType: ['Core', 'Strength'],
    description: 'Variação da prancha tradicional onde se alterna o toque da mão no ombro oposto, aumentando o desafio de estabilização.',
    instructions: ['Comece na posição de prancha alta (mãos diretamente abaixo dos ombros, corpo reto).', 'Mantenha o quadril estável e evite balançar.', 'Lentamente, leve uma mão para tocar o ombro oposto.', 'Retorne a mão ao chão e repita com o outro lado.', 'Alterne continuamente durante o tempo determinado.'],
    tips: ['Quanto mais lento o movimento, maior o desafio para o core.', 'Afaste os pés para maior estabilidade, se necessário.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'jumping-jacks',
    name: 'Polichinelos',
    emoji: '🤸‍♀️',
    muscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Full Body'],
    workoutType: ['Cardio', 'Warm-up'],
    description: 'Exercício cardiovascular clássico que envolve saltar para uma posição com as pernas abertas e as mãos se tocando acima da cabeça.',
    instructions: ['Comece em pé com os pés juntos e os braços ao lado do corpo.', 'Em um movimento, salte abrindo as pernas além da largura dos ombros e elevando os braços lateralmente até que as mãos se encontrem acima da cabeça.', 'Salte novamente para retornar à posição inicial.', 'Repita em um ritmo constante.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'burpees',
    name: 'Burpees',
    emoji: '🥵',
    muscleGroup: 'Full Body',
    secondaryMuscleGroups: ['Cardio'],
    workoutType: ['Cardio', 'Strength', 'HIIT'],
    description: 'Exercício de corpo inteiro altamente intenso que combina agachamento, prancha, flexão (opcional) e salto.',
    instructions: [
        'Agache, jogue os pés para trás.',
        'Faça uma flexão.',
        'Salte para cima (para perto das mãos e depois verticalmente).',
        'Aterrisse suavemente e repita.'
    ],
    tips: [
        'Erro: Joelhos valgos no salto.',
        'Regra: Velocidade > perfeição!',
        'Mantenha um ritmo que consiga sustentar.',
        'Pode ser modificado removendo a flexão ou o salto vertical.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'ab-wheel-mobility-abdominal',
    name: 'Mobilidade Abdominal com Rodinha',
    emoji: '⚙️',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Flexibility'],
    workoutType: ['Flexibility', 'Mobilidade'],
    description: 'Uso da rodinha abdominal para massagem e liberação miofascial da região abdominal.',
    instructions: ['Deite-se de bruços.', 'Posicione a rodinha abdominal sob o seu abdômen.', 'Role lentamente a rodinha para cima e para baixo e de um lado para o outro sobre a região abdominal, aplicando uma pressão suave.', 'Concentre-se em áreas de tensão, respirando profundamente.'],
    tips: ['Seja gentil, especialmente no início.', 'Evite rolar sobre ossos ou áreas muito sensíveis.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'superband-inverted-row',
    name: 'Remada invertida com Superband',
    emoji: '💪',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Biceps'],
    workoutType: ['Strength', 'Warm-up', 'Calisthenics'],
    description: 'Variação da remada invertida utilizando uma superband para ajustar a dificuldade ou como ponto de ancoragem.',
    instructions: ['Fixe uma superband em um suporte baixo e estável, ou use-a para auxiliar o movimento em uma barra.', 'Segure a banda (ou a barra) com as mãos na largura dos ombros.', 'Posicione o corpo inclinado para trás, com os calcanhares no chão e o corpo reto.', 'Puxe o peito em direção ao ponto de ancoragem, contraindo as costas.', 'Desça controladamente.'],
    tips: ['Quanto mais horizontal o corpo, mais difícil o exercício.', 'Mantenha o core firme.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'cat-cow-stretch',
    name: 'Alongamento Gato-Vaca',
    emoji: '🧘',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Abs'],
    workoutType: ['Flexibility', 'Warm-up', 'Yoga'],
    description: 'Movimento de yoga que alonga e aquece a coluna vertebral.',
    instructions: ['Comece na posição de quatro apoios (mãos e joelhos no chão).', 'Inspire, arqueando as costas para baixo e elevando a cabeça e o cóccix (postura da vaca).', 'Expire, arredondando as costas para cima, levando o queixo ao peito e o cóccix para baixo (postura do gato).', 'Alterne entre as duas posturas de forma fluida.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'ring-pull-up',
    name: 'Pull-Up nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Biceps', 'Shoulders', 'Abs'],
    workoutType: ['Strength', 'Hypertrophy', 'Calisthenics'],
    description: 'Pull-up (barra fixa) realizado em argolas, permitindo um movimento mais natural das articulações e maior recrutamento de estabilizadores.',
    instructions: [
        'Segure as argolas com as palmas para você (ou pronada/neutra).',
        'Puxe até o queixo passar das mãos.',
        'Desça de forma controlada até a extensão total dos braços.'
    ],
    tips: [
        'Erro: Balançar as pernas.',
        'Regra: Ative as costas, não só os braços!',
        'Mantenha o core ativado para evitar balanços excessivos.',
        'Concentre-se em puxar com os músculos das costas.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'kettlebell-bent-over-row',
    name: 'Remada Curvada (KB)',
    emoji: '🏋️',
    muscleGroup: 'Back',
    secondaryMuscleGroups: ['Biceps', 'Shoulders'],
    workoutType: ['Strength', 'Hypertrophy'],
    description: 'Exercício para as costas utilizando kettlebell, realizado com o tronco inclinado à frente.',
    instructions: [
        'Incline o tronco.',
        'Puxe o KB até a costela.',
        'Desça os kettlebells de forma controlada.'
    ],
    tips: [
        'Erro: Rotacionar o tronco.',
        'Regra: Cotovelo deve \'raspar\' no corpo!',
        'Mantenha o core firme e as costas retas para proteger a lombar.',
        'Concentre-se em usar os músculos das costas para puxar, não apenas os braços.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'superband-face-pull',
    name: 'Face Pull com Superband',
    emoji: '💪',
    muscleGroup: 'Shoulders',
    secondaryMuscleGroups: ['Back'],
    workoutType: ['Hypertrophy', 'Strength', 'Corrective'],
    description: 'Exercício excelente para a saúde dos ombros e fortalecimento do manguito rotador e trapézios mediais/inferiores, usando uma superband.',
    instructions: ['Fixe uma superband em um ponto de ancoragem na altura do peito ou rosto.', 'Segure as extremidades da banda com as duas mãos, palmas para baixo ou neutras.', 'Afaste-se para criar tensão na banda.', 'Puxe a banda em direção ao seu rosto, mantendo os cotovelos altos e para fora, até que as mãos estejam ao lado das orelhas.', 'Aperte as omoplatas juntas na parte de trás do movimento.', 'Retorne lentamente à posição inicial.'],
    tips: ['Concentre-se na rotação externa dos ombros.', 'Não use impulso; o movimento deve ser controlado.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'ab-wheel-rollout-standing',
    name: 'Rollout em Pé (Avançado)',
    emoji: '⚙️',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Full Body', 'Core'],
    workoutType: ['Strength', 'Core', 'Advanced'],
    description: 'Variação extremamente avançada do rollout com rodinha, realizada a partir da posição em pé. Requer grande força e controle do core.',
    instructions: [
        'De pé, role a rodinha para frente.',
        'Mantenha o corpo reto.',
        'Use a força do core para reverter o movimento e rolar a rodinha de volta até ficar em pé novamente.'
    ],
    tips: [
        'Erro: Deixar a lombar cair.',
        'Regra: Abdômen contraído = escudo contra lesões!',
        'O rollout em pé é como jogar Dark Souls: só tente se já zerou a versão fácil.',
        'Comece com uma amplitude muito pequena e aumente gradualmente ao longo de semanas ou meses.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  {
    id: 'ring-plank',
    name: 'Prancha nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Shoulders', 'Full Body', 'Core'],
    workoutType: ['Core', 'Strength', 'Calisthenics'],
    description: 'Posição de prancha mantida com as mãos ou antebraços em argolas, aumentando significativamente o desafio de estabilização.',
    instructions: [
        'Apoie os antebraços nas argolas.',
        'Mantenha o corpo alinhado.',
        'Sustente a posição pelo tempo desejado.'
    ],
    tips: [
        'Erro: Quadris muito altos/baixos.',
        'Regra: Imagine uma linha reta dos tornozelos à cabeça!',
        'Concentre-se em manter as argolas paradas e o corpo estável.',
        'Respire normalmente.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract nature',
    isCustom: false,
  },
  {
    id: 'kettlebell-russian-twist',
    name: 'Russian Twist (KB)',
    emoji: '🔄',
    muscleGroup: 'Abs',
    secondaryMuscleGroups: ['Obliques', 'Core'],
    workoutType: ['Core', 'Strength'],
    description: 'Exercício para os oblíquos e core, realizado sentado com o tronco inclinado para trás, torcendo o torso de um lado para o outro segurando um kettlebell.',
    instructions: ['Sente-se no chão com os joelhos dobrados e os pés levemente levantados do chão (ou apoiados para facilitar).', 'Incline o tronco para trás em cerca de 45 graus, mantendo as costas retas.', 'Segure um kettlebell com as duas mãos na frente do peito.', 'Torça o tronco lentamente para um lado, tocando (ou quase tocando) o kettlebell no chão ao lado do quadril.', 'Retorne ao centro e torça para o outro lado.', 'Continue alternando os lados.'],
    tips: ['Mantenha o movimento controlado, focando na contração dos oblíquos.', 'Evite usar impulso com os braços; o movimento deve vir do tronco.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abstract animal',
    isCustom: false,
  },
  // New exercises from the plan
  {
    id: 'chest-release-wheel',
    name: 'Liberação de Peitoral (Rodinha)',
    emoji: '🧘',
    muscleGroup: 'Chest',
    workoutType: ['Flexibility', 'Mobilidade'],
    description: 'Liberação miofascial para o peitoral utilizando a rodinha abdominal.',
    instructions: ["Deite sobre a Rodinha Abdominal.", "Role lentamente sobre o peito."],
    tips: ["Erro: Pressão excessiva.", "Regra: Respire e solte a tensão."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'chest mobility',
    isCustom: false,
  },
  {
    id: 'hamstring-stretch-seated',
    name: 'Alongamento de Isquiotibiais (Sentado)',
    emoji: '🧘',
    muscleGroup: 'Hamstrings',
    secondaryMuscleGroups: ['Legs'],
    workoutType: ['Flexibility', 'Cooldown'],
    description: 'Alongamento para os músculos isquiotibiais, realizado sentado.',
    instructions: ["Sente-se e estique as pernas.", "Alcance os pés com as mãos."],
    tips: ["Erro: Forçar a coluna.", "Regra: Mantenha a respiração calma."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'hamstring stretch',
    isCustom: false,
  },
  {
    id: 'hip-mobility-wheel',
    name: 'Mobilidade de Quadril (Rodinha)',
    emoji: '🧘',
    muscleGroup: 'Hips',
    secondaryMuscleGroups: ['Glutes'],
    workoutType: ['Flexibility', 'Mobilidade'],
    description: 'Liberação miofascial para os glúteos e quadril utilizando a rodinha abdominal.',
    instructions: ["Sente-se sobre a rodinha.", "Role lentamente nos glúteos."],
    tips: ["Erro: Pressão em áreas ósseas.", "Regra: Use o peso do corpo para liberar tensão."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'hip mobility',
    isCustom: false,
  },
  {
    id: 'jump-squat',
    name: 'Agachamento com Salto',
    emoji: '🤸‍♀️',
    muscleGroup: 'Legs',
    secondaryMuscleGroups: ['Glutes', 'Cardio'],
    workoutType: ['Plyometrics', 'Strength', 'Cardio'],
    description: 'Agachamento explosivo seguido de um salto vertical para desenvolver potência nas pernas.',
    instructions: ["Agache até 90º (ou coxas paralelas ao chão).", "Salte o mais alto possível, estendendo completamente o corpo."],
    tips: ["Erro: Aterrissar com os joelhos travados.", "Regra: Aterrisse como um gato, não como um elefante! (Suavemente, absorvendo o impacto)."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'jump squat',
    isCustom: false,
  },
];
