
import type { Exercise } from '@/types';

export const PRELOADED_EXERCISES: Exercise[] = [
  {
    id: 'bench-press',
    name: 'Supino Reto com Barra',
    emoji: '🏋️',
    muscleGroup: 'Peito',
    secondaryMuscleGroups: ['Ombros', 'Tríceps'],
    workoutType: ['Força', 'Hipertrofia', 'Powerlifting', 'Fisiculturismo'],
    description: 'Um exercício composto que trabalha o peito, ombros e tríceps. Deite-se em um banco e abaixe uma barra até o peito, depois empurre-a de volta para cima.',
    instructions: [
      'Deite-se em um banco reto com os pés firmemente no chão.',
      'Segure a barra com as mãos ligeiramente mais afastadas que a largura dos ombros.',
      'Abaixe a barra lentamente até o meio do peito, mantendo os cotovelos ligeiramente flexionados em cerca de 45 graus.',
      'Empurre a barra de volta para cima até que os braços estejam totalmente esticados, sem travar os cotovelos.',
    ],
    tips: ['Mantenha os glúteos no banco e uma leve curvatura na parte inferior das costas.', 'Controle o peso durante todo o movimento.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'supino barra',
    isCustom: false,
  },
  {
    id: 'squat',
    name: 'Agachamento com Barra',
    emoji: '🦵',
    muscleGroup: 'Pernas',
    secondaryMuscleGroups: ['Glúteos', 'Costas'],
    workoutType: ['Força', 'Hipertrofia', 'Powerlifting', 'Fisiculturismo'],
    description: 'Um exercício composto fundamental que visa principalmente os quadríceps, isquiotibiais e glúteos. Envolve agachar com uma barra nas costas.',
    instructions: [
      'Fique em pé com os pés afastados na largura dos ombros, dedos apontando ligeiramente para fora.',
      'Descanse a barra na parte superior das costas (trapézios), não no pescoço.',
      'Mantendo o peito para cima e as costas retas, abaixe os quadris como se fosse sentar em uma cadeira.',
      'Desça até que as coxas estejam pelo menos paralelas ao chão.',
      'Impulsione-se pelos calcanhares para retornar à posição inicial.',
    ],
    tips: ['Contraia o core durante todo o levantamento.', 'Certifique-se de que seus joelhos sigam a linha dos dedos dos pés.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'agachamento barra',
    isCustom: false,
  },
  {
    id: 'deadlift',
    name: 'Levantamento Terra',
    emoji: '💪',
    muscleGroup: 'Costas',
    secondaryMuscleGroups: ['Pernas', 'Glúteos', 'Corpo Inteiro'],
    workoutType: ['Força', 'Powerlifting', 'Corpo Inteiro'],
    description: 'Um exercício composto que trabalha múltiplos grupos musculares, incluindo costas, pernas e glúteos. Envolve levantar uma barra do chão para uma posição em pé.',
    instructions: [
      'Fique com o meio do pé sob a barra.',
      'Dobre nos quadris e joelhos e segure a barra com as mãos um pouco para fora das pernas.',
      'Mantenha as costas retas, o peito para cima e olhe para frente.',
      'Levante a barra estendendo os quadris e joelhos, mantendo a barra perto do corpo.',
      'Fique ereto com os ombros para trás no topo.',
      'Abaixe a barra revertendo o movimento, mantendo as costas retas.',
    ],
    tips: ['Prepare o core antes de levantar.', 'Não curve a parte inferior das costas.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'levantamento terra',
    isCustom: false,
  },
  {
    id: 'overhead-press',
    name: 'Desenvolvimento com Barra',
    emoji: '⬆️',
    muscleGroup: 'Ombros',
    secondaryMuscleGroups: ['Tríceps', 'Abdômen'],
    workoutType: ['Força', 'Hipertrofia', 'Fisiculturismo'],
    description: 'Um exercício composto que trabalha os ombros e tríceps. Envolve empurrar uma barra ou halteres acima da cabeça a partir de uma posição em pé ou sentada.',
    instructions: [
      'Fique em pé com a barra na altura dos ombros, mãos um pouco mais afastadas que a largura dos ombros.',
      'Contraia o core e os glúteos.',
      'Empurre a barra diretamente acima da cabeça até que os braços estejam totalmente esticados.',
      'Abaixe a barra de volta à altura dos ombros de forma controlada.',
    ],
    tips: ['Evite abrir muito os cotovelos.', 'Mantenha o core firme para evitar arquear as costas excessivamente.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'desenvolvimento ombros',
    isCustom: false,
  },
  {
    id: 'pull-up',
    name: 'Barra Fixa',
    emoji: '🤸',
    muscleGroup: 'Costas',
    secondaryMuscleGroups: ['Bíceps', 'Ombros'],
    workoutType: ['Força', 'Fisiculturismo', 'Calistenia'],
    description: 'Um exercício com o peso do corpo que trabalha a parte superior das costas e os bíceps. Envolve puxar o corpo para cima até que o queixo esteja sobre uma barra.',
    instructions: [
      'Segure a barra de barra fixa com as mãos em pronação (palmas para frente), um pouco mais afastadas que a largura dos ombros.',
      'Fique pendurado com os braços totalmente esticados.',
      'Puxe o corpo para cima apertando as omoplatas e ativando os dorsais.',
      'Continue até que o queixo esteja sobre a barra.',
      'Abaixe o corpo lentamente de volta à posição inicial.',
    ],
    tips: ['Evite usar impulso (kipping), a menos que esteja treinando especificamente para isso.', 'Amplitude total de movimento é fundamental.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'barra fixa',
    isCustom: false,
  },
  {
    id: 'running',
    name: 'Corrida',
    emoji: '🏃',
    muscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Pernas'],
    workoutType: ['Cardio', 'Resistência'],
    description: 'Uma forma popular de exercício aeróbico. Pode ser feita ao ar livre ou em esteira.',
    instructions: [
      'Mantenha uma postura ereta.',
      'Aterrisse com o meio do pé para reduzir o impacto.',
      'Mantenha um ritmo consistente adequado ao seu nível de condicionamento.',
    ],
    tips: ['Calçados adequados para corrida são importantes.', 'Mantenha-se hidratado.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'corrida cardio',
    isCustom: false,
  },
  {
    id: 'plank',
    name: 'Prancha',
    emoji: '🧍',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Corpo Inteiro'],
    workoutType: ['Força', 'Core'],
    description: 'Um exercício isométrico de força do core que envolve manter uma posição semelhante a uma flexão pelo maior tempo possível.',
    instructions: [
      'Deite-se de bruços e coloque os antebraços no chão, cotovelos diretamente abaixo dos ombros.',
      'Levante os quadris do chão, criando uma linha reta da cabeça aos calcanhares.',
      'Contraia o core e os glúteos.',
      'Mantenha a posição pelo tempo desejado.',
    ],
    tips: ["Não deixe os quadris caírem ou subirem muito.", 'Respire de forma constante.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'prancha abdominal',
    isCustom: false,
  },
  {
    id: 'superband-shoulder-rotation',
    name: 'Rotação de Ombros com Superband',
    emoji: '🔄',
    muscleGroup: 'Ombros',
    workoutType: ['Aquecimento', 'Flexibilidade', 'Mobilidade'],
    description: 'Aquecimento para os ombros utilizando uma superband para rotação, melhorando a mobilidade articular.',
    instructions: ['Segure a banda com as mãos afastadas, palmas para baixo.', 'Mantendo os braços esticados ou levemente flexionados, eleve a banda acima da cabeça e para trás, o mais longe que conseguir sem dor.', 'Retorne o movimento pela frente.', 'Gire os ombros para trás e para frente, mantendo os braços esticados ou levemente flexionados.'],
    tips: ['Mantenha o movimento controlado.', 'Não arqueie as costas excessivamente.', 'Regra: Imagine que está virando uma maçaneta gigante!'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ombros superband',
    isCustom: false,
  },
  {
    id: 'incline-push-up',
    name: 'Flexão Inclinada',
    emoji: '💪',
    muscleGroup: 'Peito',
    secondaryMuscleGroups: ['Ombros', 'Tríceps'],
    workoutType: ['Aquecimento', 'Força'],
    description: 'Uma variação mais fácil da flexão tradicional, realizada com as mãos em uma superfície elevada, ideal para iniciantes ou aquecimento.',
    instructions: ['Posicione as mãos em uma superfície elevada (banco, parede, caixa), um pouco mais largas que os ombros.', 'Mantenha o corpo reto da cabeça aos calcanhares, core ativado.', 'Desça o peito em direção à superfície dobrando os cotovelos.', 'Empurre de volta à posição inicial, estendendo os braços.'],
    tips: ['Mantenha o core ativado.', 'Controle a descida e a subida.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'flexao inclinada',
    isCustom: false,
  },
  {
    id: 'ring-push-up',
    name: 'Flexão nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Peito',
    secondaryMuscleGroups: ['Ombros', 'Tríceps', 'Abdômen'],
    workoutType: ['Força', 'Hipertrofia', 'Calistenia'],
    description: 'Flexão realizada com as mãos em argolas de ginástica, aumentando a instabilidade e o recrutamento muscular do peito, ombros e tríceps.',
    instructions: [
        'Apoie as mãos nas argolas, ajuste a altura para que fiquem próximas ao chão.',
        'Mantenha o corpo reto, core ativado. Cotovelos a aproximadamente 45 graus do corpo.',
        'Desça até o peito chegar na altura das mãos, ou o mais próximo possível, controlando o movimento.',
        'Suba explosivamente, empurrando as argolas para baixo e juntando-as ligeiramente no topo.'
    ],
    tips: [
        'Mantenha o core ativado para estabilizar o corpo.',
        'Ajuste a altura das argolas para modificar a dificuldade.',
        'Erro: Deixar os quadris caírem ou o corpo balançar excessivamente.',
        'Regra: Core = cinto de segurança do movimento!',
        'Hack: Contraia glúteos.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'flexao argolas',
    isCustom: false,
  },
  {
    id: 'kettlebell-clean-press',
    name: 'Kettlebell Clean & Press',
    emoji: '🏋️',
    muscleGroup: 'Corpo Inteiro',
    secondaryMuscleGroups: ['Ombros', 'Pernas', 'Tríceps', 'Core'],
    workoutType: ['Força', 'Powerlifting', 'Corpo Inteiro', 'CrossFit'],
    description: 'Exercício composto que trabalha força e potência, movendo o kettlebell do chão para o ombro (clean) e depois empurrando-o acima da cabeça (press).',
    instructions: [
        'Posicione o kettlebell entre os pés.',
        'Faça um swing com o quadril para trás e puxe o KB do chão, guiando-o para a posição de rack no ombro (clean). O cotovelo deve ficar próximo ao corpo.',
        'Do ombro, estabilize e empurre o kettlebell para cima até o braço esticar completamente.',
        'Retorne o kettlebell ao ombro com controle e depois ao chão (ou para o próximo clean).',
        'Repita para o número desejado de repetições e depois troque o lado.'
    ],
    tips: [
        'Mantenha o core firme durante todo o movimento.',
        'Use as pernas e o quadril para gerar força no clean.',
        'Erro: Girar o pulso na subida do clean ou deixar o KB bater no antebraço.',
        'Regra (Clean): Cotovelo grudado no corpo na fase de puxar!'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kettlebell cleanpress',
    isCustom: false,
  },
  {
    id: 'kettlebell-press',
    name: 'Kettlebell Press',
    emoji: '🏋️',
    muscleGroup: 'Ombros',
    secondaryMuscleGroups: ['Tríceps', 'Core'],
    workoutType: ['Força', 'Hipertrofia'],
    description: 'Exercício para desenvolvimento de força e massa muscular nos ombros e tríceps, pressionando um kettlebell acima da cabeça a partir da posição de rack (ombro).',
    instructions: [
      'Segure o kettlebell na posição de rack no ombro, com o cotovelo próximo ao corpo e o KB descansando no antebraço e ombro.',
      'Mantenha o core ativado e os pés firmes no chão.',
      'Empurre o kettlebell verticalmente para cima até o braço estar completamente esticado.',
      'Controle a descida do kettlebell de volta à posição de rack no ombro.'
    ],
    tips: [
      'Mantenha o punho reto e alinhado com o antebraço.',
      'Evite arquear excessivamente as costas; expire ao empurrar.',
      'Concentre-se em usar a força do ombro e do tríceps.',
      'Erro: Arquear costas.',
      'Hack: Expire ao empurrar.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kettlebell press',
    isCustom: false,
  },
  {
    id: 'ring-dip',
    name: 'Mergulho nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Tríceps',
    secondaryMuscleGroups: ['Peito', 'Ombros'],
    workoutType: ['Força', 'Hipertrofia', 'Calistenia'],
    description: 'Exercício desafiador para o tríceps, peito e ombros, utilizando argolas de ginástica para instabilidade.',
    instructions: ['Comece com os braços esticados, segurando as argolas, corpo suspenso e estável.', 'Mantenha as argolas próximas ao corpo.', 'Desça lentamente dobrando os cotovelos, até que os ombros cheguem aproximadamente na altura das mãos ou cotovelos formem um ângulo de 90 graus.', 'Empurre de volta à posição inicial, estendendo completamente os braços.'],
    tips: ['Mantenha o core ativado para evitar balanços.', 'Evite que os ombros rolem para frente; mantenha o peito aberto.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'mergulho argolas',
    isCustom: false,
  },
  {
    id: 'superband-triceps-pushdown',
    name: 'Tríceps na Superband',
    emoji: '💪',
    muscleGroup: 'Tríceps',
    workoutType: ['Força', 'Hipertrofia', 'Aquecimento'],
    description: 'Exercício de isolamento para o tríceps utilizando uma superband fixada em um ponto alto, focando na extensão do cotovelo.',
    instructions: ['Fixe a superband em um ponto alto e seguro (ex: barra de pull-up).', 'Segure as extremidades da banda com as duas mãos, palmas para baixo ou neutras, cotovelos próximos ao corpo.', 'Comece com os antebraços paralelos ao chão ou levemente acima.', 'Empurre a banda para baixo até que os braços estejam totalmente estendidos.', 'Retorne lentamente à posição inicial, controlando a tensão da banda.'],
    tips: ['Mantenha os cotovelos fixos ao lado do corpo, evitando que se abram.', 'Concentre-se na contração do tríceps no final do movimento.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'triceps superband',
    isCustom: false,
  },
  {
    id: 'bodyweight-squat',
    name: 'Agachamento Livre',
    emoji: '🦵',
    muscleGroup: 'Pernas',
    secondaryMuscleGroups: ['Glúteos', 'Core'],
    workoutType: ['Aquecimento', 'Força', 'Calistenia', 'Mobilidade'],
    description: 'Agachamento utilizando apenas o peso do corpo, fundamental para aquecimento, treino de pernas e desenvolvimento de padrão de movimento.',
    instructions: ['Fique em pé com os pés na largura dos ombros, pontas dos pés levemente para fora.', 'Mantenha o peito erguido, costas retas e o core ativado.', 'Agache como se fosse sentar em uma cadeira, levando o quadril para trás e para baixo, até que as coxas fiquem paralelas ao chão ou mais baixo, se possível.', 'Mantenha os calcanhares no chão.', 'Empurre com os calcanhares para voltar à posição inicial.'],
    tips: ['Mantenha os joelhos alinhados com os pés, não deixe que entrem.', 'Costas retas durante todo o movimento.', 'A profundidade é importante para ativação dos glúteos.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'agachamento livre',
    isCustom: false,
  },
  {
    id: 'dead-bug',
    name: 'Cachorro Morto (Dead Bug)',
    emoji: '🐞',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Core'],
    workoutType: ['Core', 'Aquecimento', 'Flexibilidade', 'Mobilidade'],
    description: 'Exercício de core que melhora a estabilidade lombar e coordenação, mantendo a lombar pressionada contra o chão enquanto membros opostos se movem.',
    instructions: ['Deite-se de costas com os joelhos dobrados a 90 graus (acima do quadril) e os braços estendidos em direção ao teto (acima dos ombros).', 'Mantenha a lombar pressionada firmemente contra o chão (core ativado).', 'Estenda lentamente um braço para trás da cabeça (em direção ao chão) e a perna oposta em direção ao chão, sem tocar.', 'Retorne à posição inicial de forma controlada e repita com o outro lado (braço e perna opostos).'],
    tips: ['Mantenha o core sempre contraído para evitar que a lombar arqueie.', 'Movimentos lentos e controlados são mais eficazes.', 'Se sentir a lombar arquear, reduza a amplitude do movimento.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dead bug',
    isCustom: false,
  },
  {
    id: 'kettlebell-goblet-squat',
    name: 'Agachamento Goblet (KB)',
    emoji: '🏋️',
    muscleGroup: 'Pernas',
    secondaryMuscleGroups: ['Glúteos', 'Abdômen', 'Core'],
    workoutType: ['Força', 'Hipertrofia', 'Corpo Inteiro'],
    description: 'Variação do agachamento onde um kettlebell é segurado na frente do peito, ajudando a manter o tronco ereto e engajando o core.',
    instructions: [
        'Segure o KB pelas laterais da alça (chifres) ou pela base, encostado no peito.',
        'Mantenha os pés na largura dos ombros ou um pouco mais afastados, pontas para fora.',
        'Agache até as coxas ficarem paralelas ao chão ou mais baixo, mantendo o peito alto e as costas retas.',
        'Empurre com os calcanhares para retornar à posição inicial, estendendo completamente os quadris e joelhos.'
    ],
    tips: [
        'Mantenha o kettlebell próximo ao corpo.',
        'A profundidade é importante; tente quebrar a paralela se sua mobilidade permitir.',
        'Erro: Joelhos para dentro ou tronco caindo para frente.',
        'Regra: Empurre o chão com os calcanhares! Use os cotovelos para afastar os joelhos, se necessário, na parte inferior do agachamento.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'agachamento goblet',
    isCustom: false,
  },
  {
    id: 'single-leg-hip-thrust',
    name: 'Ponte Glútea (1 perna)',
    emoji: '🦵',
    muscleGroup: 'Glúteos',
    secondaryMuscleGroups: ['Isquiotibiais', 'Core'],
    workoutType: ['Força', 'Hipertrofia', 'Calistenia'],
    description: 'Exercício unilateral para glúteos, realizado deitado, elevando o quadril com apoio em uma perna e o pé da outra perna fora do chão.',
    instructions: [
        'Deite-se de barriga para cima com os joelhos dobrados e os pés apoiados no chão, próximos aos glúteos.',
        'Estenda uma perna para cima ou mantenha o joelho dobrado com o pé fora do chão.',
        'Empurre o calcanhar da perna de apoio contra o chão e eleve o quadril, contraindo o glúteo da perna de apoio.',
        'Eleve o quadril até formar uma linha reta dos ombros aos joelhos.',
        'Segure por um momento no topo, se indicado.',
        'Desça controladamente e repita. Troque de perna após as repetições.'
    ],
    tips: [
        'Concentre-se em usar o glúteo para levantar o quadril, não a lombar.',
        'Mantenha o core ativado para estabilizar.',
        'Erro: Deixar o quadril descer ou rodar.',
        'Regra: Contraia glúteos como se estivesse segurando uma nota de R$100!'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ponte glutea',
    isCustom: false,
  },
  {
    id: 'ab-wheel-rollout-kneeling',
    name: 'Rollout com Rodinha (Ajoelhado)',
    emoji: '⚙️',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Ombros', 'Costas', 'Core', 'Corpo Inteiro'],
    workoutType: ['Força', 'Core'],
    description: 'Exercício intenso para o core utilizando a rodinha abdominal, partindo da posição ajoelhada. Fortalece e desafia toda a musculatura anterior do tronco.',
    instructions: [
        'Ajoelhado em uma superfície macia, segure a rodinha com as duas mãos diretamente abaixo dos ombros.',
        'Mantendo o core fortemente contraído, role a rodinha para frente, estendendo o corpo o máximo que conseguir sem perder a forma (sem arquear a lombar).',
        'Os braços e o tronco devem se mover juntos.',
        'Use a força do core para reverter o movimento e rolar a rodinha de volta à posição inicial.'
    ],
    tips: [
        'Mantenha o core TÃO TENSIONADO quanto sua cara ao ver o preço do açaí.',
        'Não deixe a lombar cair, isso é um convite para dor nas costas.',
        'Comece com uma amplitude menor e aumente conforme ganha força.',
        'Erro: Arquear a lombar ou usar demais os flexores do quadril para voltar.',
        'Regra: Abdômen mais duro que a realidade! Mantenha o nariz alinhado com o umbigo durante o movimento para ajudar a manter a coluna neutra.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'rollout rodinha',
    isCustom: false,
  },
  {
    id: 'dynamic-plank-shoulder-taps',
    name: 'Prancha Dinâmica (Toque no Ombro)',
    emoji: '🧍‍♂️',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Ombros', 'Corpo Inteiro', 'Core', 'Tríceps'],
    workoutType: ['Core', 'Força', 'Aquecimento'],
    description: 'Variação da prancha tradicional onde se alterna o toque da mão no ombro oposto, aumentando o desafio de estabilização anti-rotacional do core.',
    instructions: ['Comece na posição de prancha alta (mãos diretamente abaixo dos ombros, corpo reto dos calcanhares à cabeça).', 'Mantenha o quadril estável e evite balançar o corpo lateralmente.', 'Lentamente, levante uma mão do chão e toque o ombro oposto.', 'Retorne a mão ao chão de forma controlada e repita com o outro lado.', 'Alterne continuamente durante o tempo determinado.'],
    tips: ['Quanto mais lento o movimento, maior o desafio para o core.', 'Afaste os pés para maior estabilidade, se necessário.', 'Concentre-se em manter o umbigo apontado para o chão.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'prancha toque',
    isCustom: false,
  },
  {
    id: 'jumping-jacks',
    name: 'Polichinelos',
    emoji: '🤸‍♀️',
    muscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Corpo Inteiro', 'Pernas', 'Ombros'],
    workoutType: ['Cardio', 'Aquecimento', 'HIIT'],
    description: 'Exercício cardiovascular clássico que envolve saltar para uma posição com as pernas abertas e as mãos se tocando (ou quase) acima da cabeça.',
    instructions: ['Comece em pé com os pés juntos e os braços ao lado do corpo.', 'Em um movimento coordenado, salte abrindo as pernas para além da largura dos ombros enquanto eleva os braços lateralmente até que as mãos se encontrem (ou cheguem perto) acima da cabeça.', 'Salte novamente, retornando os pés à posição inicial e os braços ao lado do corpo.', 'Repita em um ritmo constante.'],
    tips: ['Mantenha um ritmo que consiga sustentar.', 'Aterrisse suavemente na ponta dos pés.', 'Pode ser usado como aquecimento ou parte de um treino HIIT.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'polichinelos cardio',
    isCustom: false,
  },
  {
    id: 'burpees',
    name: 'Burpees',
    emoji: '🥵',
    muscleGroup: 'Corpo Inteiro',
    secondaryMuscleGroups: ['Cardio', 'Pernas', 'Peito', 'Ombros', 'Abdômen'],
    workoutType: ['Cardio', 'Força', 'HIIT', 'CrossFit'],
    description: 'Exercício de corpo inteiro altamente intenso que combina agachamento, prancha, flexão (opcional) e salto vertical.',
    instructions: [
        'Comece em pé, agache e coloque as mãos no chão à frente dos pés.',
        'Salte os pés para trás, entrando na posição de prancha.',
        'Opcional: realize uma flexão completa (peito toca o chão).',
        'Salte os pés de volta para perto das mãos.',
        'Salte verticalmente o mais alto que puder, estendendo os braços acima da cabeça.',
        'Aterrisse suavemente e repita.'
    ],
    tips: [
        'Mantenha um ritmo que consiga sustentar, mas desafiador.',
        'Pode ser modificado removendo a flexão ou o salto vertical para iniciantes.',
        'Erro: Joelhos valgos (para dentro) no agachamento ou salto. Costas curvadas.',
        'Regra: Velocidade é bom, mas a forma vem primeiro para evitar lesões!'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'burpees hiit',
    isCustom: false,
  },
  {
    id: 'ab-wheel-mobility-abdominal',
    name: 'Mobilidade Abdominal com Rodinha',
    emoji: '⚙️',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Flexibilidade', 'Core'],
    workoutType: ['Flexibilidade', 'Mobilidade', 'Desaquecimento'],
    description: 'Uso da rodinha abdominal para massagem suave e liberação miofascial da região abdominal, promovendo mobilidade.',
    instructions: ['Deite-se de bruços ou fique de quatro.', 'Posicione a rodinha abdominal sob o seu abdômen.', 'Role lentamente a rodinha para cima e para baixo e de um lado para o outro sobre a região abdominal, aplicando uma pressão suave e controlada.', 'Concentre-se em áreas de tensão, respirando profundamente.'],
    tips: ['Seja gentil, especialmente no início; evite pressão excessiva.', 'Evite rolar sobre ossos (costelas, quadril) ou áreas muito sensíveis.', 'Este não é um exercício de fortalecimento, mas de mobilidade e liberação.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abdominal rodinha',
    isCustom: false,
  },
  {
    id: 'superband-inverted-row',
    name: 'Remada invertida com Superband',
    emoji: '💪',
    muscleGroup: 'Costas',
    secondaryMuscleGroups: ['Bíceps', 'Ombros'],
    workoutType: ['Força', 'Aquecimento', 'Calistenia'],
    description: 'Variação da remada invertida utilizando uma superband para ajustar a dificuldade ou como ponto de ancoragem em uma barra baixa.',
    instructions: ['Fixe uma superband em um suporte baixo e estável (ex: poste, rack), ou passe-a por uma barra baixa.', 'Segure a banda (ou a barra com a banda auxiliando) com as mãos na largura dos ombros, palmas para baixo ou para cima.', 'Posicione o corpo inclinado para trás, com os calcanhares no chão e o corpo reto dos tornozelos à cabeça.', 'Puxe o peito em direção ao ponto de ancoragem (ou à barra), contraindo as omoplatas.', 'Desça controladamente até os braços estarem quase esticados.'],
    tips: ['Quanto mais horizontal o corpo, mais difícil o exercício.', 'Mantenha o core firme para evitar que o quadril caia.', 'Concentre-se em puxar com os músculos das costas.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'remada superband',
    isCustom: false,
  },
  {
    id: 'cat-cow-stretch',
    name: 'Alongamento Gato-Vaca',
    emoji: '🧘',
    muscleGroup: 'Costas',
    secondaryMuscleGroups: ['Abdômen', 'Core'],
    workoutType: ['Flexibilidade', 'Aquecimento', 'Yoga', 'Mobilidade'],
    description: 'Movimento de yoga que alonga e aquece a coluna vertebral, promovendo mobilidade e aliviando tensões.',
    instructions: ['Comece na posição de quatro apoios (mãos diretamente abaixo dos ombros, joelhos diretamente abaixo do quadril).', 'Inspire, arqueando as costas para baixo (extensão da coluna), elevando a cabeça e o cóccix em direção ao teto (postura da vaca).', 'Expire, arredondando as costas para cima (flexão da coluna), levando o queixo ao peito e o cóccix para baixo (postura do gato).', 'Alterne entre as duas posturas de forma fluida, sincronizando com a respiração.'],
    tips: ['Mantenha os movimentos lentos e controlados.', 'Concentre-se na mobilidade de cada vértebra.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'gato vaca',
    isCustom: false,
  },
  {
    id: 'ring-pull-up',
    name: 'Pull-Up nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Costas',
    secondaryMuscleGroups: ['Bíceps', 'Ombros', 'Abdômen', 'Core'],
    workoutType: ['Força', 'Hipertrofia', 'Calistenia'],
    description: 'Pull-up (barra fixa) realizado em argolas, permitindo um movimento mais natural das articulações do punho e ombro, e maior recrutamento de estabilizadores.',
    instructions: [
        'Segure as argolas com as palmas para você (supinada), para frente (pronada) ou neutra (martelo). As argolas permitem rotação natural.',
        'Comece com os braços totalmente esticados (posição de pendurado).',
        'Puxe o corpo para cima, levando o peito em direção às argolas, até o queixo passar da linha das mãos.',
        'Desça de forma controlada até a extensão total dos braços.'
    ],
    tips: [
        'Mantenha o core ativado para evitar balanços excessivos.',
        'Concentre-se em puxar com os músculos das costas (lats) e bíceps.',
        'Erro: Balançar as pernas para ganhar impulso (a menos que seja um kipping pull-up intencional). Não completar a amplitude do movimento.',
        'Regra: Ative as costas, não só os braços! Imagine que está puxando os cotovelos para baixo e para trás.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'pullup argolas',
    isCustom: false,
  },
  {
    id: 'kettlebell-bent-over-row',
    name: 'Remada Curvada (KB)',
    emoji: '🏋️',
    muscleGroup: 'Costas',
    secondaryMuscleGroups: ['Bíceps', 'Ombros', 'Core'],
    workoutType: ['Força', 'Hipertrofia'],
    description: 'Exercício para as costas (principalmente dorsais e romboides) utilizando um ou dois kettlebells, realizado com o tronco inclinado à frente.',
    instructions: [
        'Segure um kettlebell em cada mão (ou um único KB com as duas mãos).',
        'Incline o tronco para frente a partir do quadril, mantendo as costas retas (aproximadamente paralelo ao chão). Joelhos levemente flexionados.',
        'Deixe os braços esticados em direção ao chão.',
        'Puxe o(s) KB(s) em direção à parte inferior do peito ou costelas, contraindo as omoplatas.',
        'Desça os kettlebells de forma controlada de volta à posição inicial.'
    ],
    tips: [
        'Mantenha o core firme e as costas retas para proteger a lombar.',
        'Concentre-se em usar os músculos das costas para puxar, não apenas os braços.',
        'Erro: Rotacionar o tronco ou usar impulso para levantar o peso. Curvar a lombar.',
        "Regra: Cotovelo deve 'raspar' no corpo (ou passar próximo a ele)!"
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'remada kettlebell',
    isCustom: false,
  },
  {
    id: 'superband-face-pull',
    name: 'Face Pull com Superband',
    emoji: '💪',
    muscleGroup: 'Ombros',
    secondaryMuscleGroups: ['Costas', 'Tríceps'],
    workoutType: ['Hipertrofia', 'Força', 'Corretivo', 'Aquecimento'],
    description: 'Exercício excelente para a saúde dos ombros, fortalecimento do manguito rotador, trapézios mediais/inferiores e deltoides posteriores, usando uma superband.',
    instructions: ['Fixe uma superband em um ponto de ancoragem na altura do peito ou rosto.', 'Segure as extremidades da banda com as duas mãos, palmas para baixo ou neutras (polegares para cima).', 'Afaste-se para criar tensão na banda.', 'Puxe a banda em direção ao seu rosto (nariz/testa), mantendo os cotovelos altos e para fora (mais altos que os punhos).', 'Conduza o movimento com os cotovelos, apertando as omoplatas juntas na parte de trás do movimento.', 'Retorne lentamente à posição inicial, controlando a tensão.'],
    tips: ['Concentre-se na rotação externa dos ombros e na retração das escápulas.', 'Não use impulso; o movimento deve ser controlado.', 'Mantenha os ombros para baixo, longe das orelhas.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'facepull superband',
    isCustom: false,
  },
  {
    id: 'ab-wheel-rollout-standing',
    name: 'Rollout em Pé (Avançado)',
    emoji: '⚙️',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Corpo Inteiro', 'Core', 'Ombros', 'Costas'],
    workoutType: ['Força', 'Core', 'Avançado', 'Calistenia'],
    description: 'Variação extremamente avançada do rollout com rodinha, realizada a partir da posição em pé. Requer grande força, controle e estabilidade do core.',
    instructions: [
        'Fique em pé com os pés na largura dos ombros, segurando a rodinha abdominal.',
        'Incline-se para frente a partir do quadril, colocando a rodinha no chão à sua frente.',
        'Mantendo o corpo reto e o core extremamente contraído, role a rodinha para frente o máximo que conseguir com controle, idealmente até o corpo estar quase paralelo ao chão.',
        'Use a força do core para reverter o movimento e rolar a rodinha de volta até ficar em pé novamente.'
    ],
    tips: [
        'Este é um exercício muito avançado. Domine completamente o rollout ajoelhado antes de tentar.',
        'Comece com uma amplitude muito pequena e aumente gradualmente ao longo de semanas ou meses.',
        'Erro: Deixar a lombar cair ou perder a tensão do core. Usar impulso excessivo.',
        'Regra: Abdômen contraído = escudo contra lesões! Se sentir qualquer desconforto na lombar, pare.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'rollout pe',
    isCustom: false,
  },
  {
    id: 'ring-plank',
    name: 'Prancha nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Ombros', 'Corpo Inteiro', 'Core', 'Tríceps'],
    workoutType: ['Core', 'Força', 'Calistenia', 'Isométrico'],
    description: 'Posição de prancha mantida com as mãos ou antebraços em argolas, aumentando significativamente o desafio de estabilização devido à instabilidade das argolas.',
    instructions: [
        'Ajuste as argolas a uma altura baixa, próxima ao chão.',
        'Apoie os antebraços (ou mãos) nas argolas.',
        'Estenda as pernas para trás, formando uma linha reta dos calcanhares à cabeça. Mantenha o corpo alinhado.',
        'Contraia o core e os glúteos para manter a estabilidade.',
        'Sustente a posição pelo tempo desejado.'
    ],
    tips: [
        'Concentre-se em manter as argolas paradas e o corpo estável.',
        'Respire normalmente durante a execução.',
        'Erro: Quadris muito altos ou muito baixos (arqueando a lombar). Deixar as argolas se moverem descontroladamente.',
        'Regra: Imagine uma linha reta dos tornozelos à cabeça! Mantenha tudo contraído.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'prancha argolas',
    isCustom: false,
  },
  {
    id: 'kettlebell-russian-twist',
    name: 'Russian Twist (KB)',
    emoji: '🔄',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Oblíquos', 'Core'],
    workoutType: ['Core', 'Força'],
    description: 'Exercício para os oblíquos e core, realizado sentado com o tronco inclinado para trás, torcendo o torso de um lado para o outro segurando um kettlebell.',
    instructions: ['Sente-se no chão com os joelhos dobrados e os pés levemente levantados do chão (ou apoiados para facilitar).', 'Incline o tronco para trás em cerca de 45 graus, mantendo as costas retas e o core ativado.', 'Segure um kettlebell com as duas mãos na frente do peito.', 'Torça o tronco lentamente para um lado, levando o kettlebell em direção ao chão ao lado do quadril.', 'Retorne ao centro e torça para o outro lado.', 'Continue alternando os lados de forma controlada.'],
    tips: ['Mantenha o movimento controlado, focando na contração dos oblíquos.', 'Evite usar impulso com os braços; o movimento deve vir do tronco.', 'Mantenha a cabeça e o peito erguidos.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'russiantwist kettlebell',
    isCustom: false,
  },
  {
    id: 'chest-release-wheel',
    name: 'Liberação de Peitoral (Rodinha)',
    emoji: '🧘',
    muscleGroup: 'Peito',
    secondaryMuscleGroups: ['Ombros'],
    workoutType: ['Flexibilidade', 'Mobilidade', 'Desaquecimento'],
    description: 'Liberação miofascial para o peitoral utilizando a rodinha abdominal para aliviar tensões e melhorar a mobilidade.',
    instructions: ["Deite-se de bruços ou de lado.", "Posicione a rodinha abdominal sob uma das laterais do seu peito.", "Use o peso do corpo para aplicar pressão e role lentamente sobre a área do peitoral.", "Concentre-se em áreas de maior tensão, respirando profundamente."],
    tips: ["Erro: Pressão excessiva ou rolar sobre áreas ósseas.", "Regra: Respire e solte a tensão. Seja gentil, especialmente no início."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'peito mobilidade',
    isCustom: false,
  },
  {
    id: 'hamstring-stretch-seated',
    name: 'Alongamento de Isquiotibiais (Sentado)',
    emoji: '🧘',
    muscleGroup: 'Isquiotibiais',
    secondaryMuscleGroups: ['Pernas', 'Costas'],
    workoutType: ['Flexibilidade', 'Desaquecimento'],
    description: 'Alongamento para os músculos isquiotibiais (posteriores da coxa), realizado sentado, que ajuda a melhorar a flexibilidade e aliviar tensões.',
    instructions: ["Sente-se no chão com as pernas esticadas à sua frente.", "Mantenha as costas retas e incline o tronco para frente a partir do quadril, tentando alcançar os pés com as mãos.", "Mantenha o alongamento por 20-30 segundos, respirando profundamente."],
    tips: ["Erro: Forçar a coluna (curvar as costas) para alcançar mais longe. Mantenha os joelhos levemente flexionados se necessário.", "Regra: Mantenha a respiração calma e constante. Sinta o alongamento na parte de trás das coxas."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'isquiotibiais alongamento',
    isCustom: false,
  },
  {
    id: 'hip-mobility-wheel',
    name: 'Mobilidade de Quadril (Rodinha)',
    emoji: '🧘',
    muscleGroup: 'Quadril',
    secondaryMuscleGroups: ['Glúteos'],
    workoutType: ['Flexibilidade', 'Mobilidade', 'Aquecimento'],
    description: 'Liberação miofascial para os glúteos e quadril utilizando a rodinha abdominal, ajudando a soltar tensões e melhorar a mobilidade da região.',
    instructions: ["Sente-se sobre a rodinha abdominal, posicionando-a sob um dos glúteos.", "Apoie-se com as mãos atrás de você e, se desejar, cruze o tornozelo do lado que está sendo trabalhado sobre o joelho oposto.", "Role lentamente sobre a área do glúteo, procurando pontos de tensão.", "Mantenha a pressão sobre os pontos tensos por alguns segundos, respirando profundamente."],
    tips: ["Erro: Pressão em áreas ósseas ou rolar muito rapidamente.", "Regra: Use o peso do corpo para controlar a pressão e liberar a tensão. Seja paciente."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'quadril mobilidade',
    isCustom: false,
  },
  {
    id: 'jump-squat',
    name: 'Agachamento com Salto',
    emoji: '🤸‍♀️',
    muscleGroup: 'Pernas',
    secondaryMuscleGroups: ['Glúteos', 'Cardio', 'Core'],
    workoutType: ['Pliometria', 'Força', 'Cardio', 'HIIT'],
    description: 'Agachamento explosivo seguido de um salto vertical para desenvolver potência nas pernas e aumentar a frequência cardíaca.',
    instructions: ["Comece em pé, pés na largura dos ombros.", "Realize um agachamento até que as coxas fiquem paralelas ao chão (ou 90 graus nos joelhos).", "Imediatamente, salte o mais alto possível, estendendo completamente o corpo (quadris, joelhos, tornozelos).", "Aterrisse suavemente, absorvendo o impacto com os joelhos flexionados, e prepare-se para o próximo salto."],
    tips: ["Erro: Aterrissar com os joelhos travados ou deixar os joelhos desalinharem.", "Regra: Aterrisse como um gato, não como um elefante! (Suavemente, absorvendo o impacto).", "Mantenha o core ativado durante todo o movimento."],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'agachamento salto',
    isCustom: false,
  },
  {
    id: 'jump-rope',
    name: 'Pular Corda',
    emoji: '🤸‍♀️',
    muscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Pernas', 'Corpo Inteiro'],
    workoutType: ['Cardio', 'Aquecimento', 'HIIT', 'Resistência'],
    description: 'Exercício cardiorrespiratório eficaz que melhora a coordenação, agilidade e resistência. Pode ser de baixa ou alta intensidade.',
    instructions: [
      'Segure as manoplas da corda, uma em cada mão, com os cotovelos próximos ao corpo.',
      'Use os pulsos e antebraços para girar a corda, não os ombros.',
      'Salte baixo, apenas o suficiente para a corda passar sob os pés. Mantenha os joelhos levemente flexionados.',
      'Aterrisse suavemente na ponta dos pés.'
    ],
    tips: [
      'Mantenha um ritmo constante e a respiração controlada.',
      'Comece com saltos básicos e progrida para variações (ex: alternando os pés, joelhos altos) conforme ganha confiança.',
      'Ajuste o comprimento da corda: pisando no meio da corda, as manoplas devem alcançar suas axilas.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'pular corda',
    isCustom: false,
  },
  {
    id: 'superband-jumps',
    name: 'Saltos com Superband',
    emoji: '🤸‍♂️',
    muscleGroup: 'Pernas',
    secondaryMuscleGroups: ['Cardio', 'Glúteos', 'Core'],
    workoutType: ['Pliometria', 'HIIT', 'Força'],
    description: 'Saltos explosivos (verticais, horizontais, etc.) realizados contra a resistência de uma superband para aumentar a potência e a força das pernas.',
    instructions: [
      'Ancore a superband em um ponto fixo e seguro (baixo para saltos verticais/horizontais com a banda na cintura) ou peça para um parceiro segurar a outra extremidade.',
      'Posicione a banda ao redor da sua cintura ou segure-a, dependendo do tipo de salto.',
      'Realize saltos explosivos (para cima, para frente, laterais) contra a resistência da banda.',
      'Concentre-se na máxima explosão em cada salto.'
    ],
    tips: [
      'Aterrisse suavemente, absorvendo o impacto.',
      'Mantenha o core ativado para estabilidade.',
      'Ajuste a tensão da banda para o nível de dificuldade desejado.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'saltos superband',
    isCustom: false,
  },
  {
    id: 'diamond-push-up',
    name: 'Flexão Diamante',
    emoji: '💎',
    muscleGroup: 'Tríceps',
    secondaryMuscleGroups: ['Peito', 'Ombros', 'Core'],
    workoutType: ['Força', 'Hipertrofia', 'Calistenia'],
    description: 'Uma variação desafiadora da flexão que foca intensamente nos tríceps, com as mãos posicionadas próximas no chão, formando um diamante com os polegares e indicadores.',
    instructions: [
      'Posicione as mãos no chão diretamente sob o peito, com os dedos indicadores e polegares se tocando para formar um formato de diamante.',
      'Estenda as pernas para trás, entrando na posição de prancha alta, corpo reto dos calcanhares à cabeça.',
      'Baixe o corpo dobrando os cotovelos, mantendo-os próximos ao corpo, até que o peito quase toque as mãos.',
      'Empurre de volta à posição inicial, estendendo completamente os braços e focando na contração do tríceps.'
    ],
    tips: [
      'Mantenha o core ativado durante todo o movimento para evitar que o quadril caia.',
      'Se for muito difícil, comece com os joelhos no chão ou realize flexões inclinadas com as mãos em diamante.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'flexao diamante',
    isCustom: false,
  },
  {
    id: 'plank-rotation',
    name: 'Prancha com Rotação',
    emoji: '🔄',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Oblíquos', 'Ombros', 'Core'],
    workoutType: ['Core', 'Força', 'Mobilidade'],
    description: 'Exercício de prancha lateral dinâmica que envolve rotação do tronco, engajando fortemente os oblíquos e melhorando a estabilidade e mobilidade do core.',
    instructions: [
      'Comece em posição de prancha lateral, apoiado no antebraço direito e na lateral do pé direito. O corpo deve formar uma linha reta.',
      'Estenda o braço esquerdo em direção ao teto.',
      'Lentamente, rotacione o tronco levando o braço esquerdo por baixo do corpo, em direção ao espaço entre o seu corpo e o chão.',
      'Reverta o movimento, retornando o braço esquerdo para o teto.',
      'Controle o movimento durante toda a amplitude.',
      'Repita pelo número desejado de repetições e depois troque de lado.'
    ],
    tips: [
      'Mantenha o quadril elevado e estável; não deixe que ele caia ou gire excessivamente.',
      'O movimento deve ser controlado e originado no core, não no braço.',
      'Mantenha o cotovelo de apoio diretamente abaixo do ombro.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'prancha rotacao',
    isCustom: false,
  },
  {
    id: 'dynamic-stretching',
    name: 'Alongamento Dinâmico',
    emoji: '🧘‍♂️',
    muscleGroup: 'Corpo Inteiro',
    workoutType: ['Aquecimento', 'Flexibilidade', 'Mobilidade'],
    description: 'Sequência de movimentos fluidos e controlados que levam as articulações e músculos através de sua amplitude de movimento completa. Prepara o corpo para o exercício.',
    instructions: [
      'Realize movimentos como balanços de perna (frontais, laterais).',
      'Círculos com os braços (para frente, para trás, grandes e pequenos).',
      'Rotações de tronco (suaves e controladas).',
      'Agachamentos com peso corporal, afundos com alcance, etc.',
      'Mantenha os movimentos controlados e progressivos, aumentando gradualmente a amplitude.',
      'Concentre-se em aquecer as principais articulações e grupos musculares que serão trabalhados na sessão.'
    ],
    tips: [
      'Não force além da sua amplitude de movimento confortável, especialmente no início.',
      'Aumente a intensidade e a amplitude gradualmente.',
      'Respire normalmente durante os movimentos.',
      'Diferente do alongamento estático, não segure as posições por longos períodos.'
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'alongamento dinamico',
    isCustom: false,
  },
  {
    id: 'reverse-grip-curl',
    name: 'Rosca Inversa com Barra',
    emoji: '💪',
    muscleGroup: 'Antebraços',
    secondaryMuscleGroups: ['Bíceps'],
    workoutType: ['Força', 'Hipertrofia'],
    description: 'Exercício para fortalecer os antebraços (principalmente extensores do punho) e o músculo braquial, utilizando uma barra com pegada pronada (palmas para baixo).',
    instructions: [
      'Segure uma barra reta ou EZ com as mãos na largura dos ombros, palmas voltadas para baixo.',
      'Mantenha os cotovelos próximos ao corpo e os braços superiores imóveis.',
      'Flexione os cotovelos, elevando a barra em direção aos ombros.',
      'Contraia os antebraços e bíceps no topo do movimento.',
      'Abaixe a barra lentamente de volta à posição inicial.'
    ],
    tips: ['Mantenha o movimento controlado, evitando balançar o corpo.', 'Concentre-se na contração dos músculos do antebraço.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'rosca inversa',
    isCustom: false,
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Elevação Lateral com Halteres',
    emoji: '🏋️‍♀️',
    muscleGroup: 'Ombros',
    secondaryMuscleGroups: ['Trapézio'],
    workoutType: ['Hipertrofia', 'Força', 'Fisiculturismo'],
    description: 'Exercício de isolamento para os deltoides laterais (parte do meio dos ombros), ajudando a criar largura nos ombros.',
    instructions: [
      'Fique em pé ou sentado, segurando um halter em cada mão ao lado do corpo, palmas voltadas para dentro.',
      'Mantenha uma leve flexão nos cotovelos.',
      'Eleve os halteres lateralmente até a altura dos ombros, mantendo os braços quase retos.',
      'Pause no topo e depois abaixe os halteres lentamente de volta à posição inicial.'
    ],
    tips: ['Evite usar impulso ou balançar o corpo.', 'Concentre-se em sentir a contração nos ombros laterais.', 'Não eleve os halteres acima da altura dos ombros.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'elevacao lateral',
    isCustom: false,
  },
  {
    id: 'dumbbell-lunge',
    name: 'Afundo com Halteres',
    emoji: '🦵',
    muscleGroup: 'Pernas',
    secondaryMuscleGroups: ['Glúteos', 'Quadríceps', 'Isquiotibiais'],
    workoutType: ['Força', 'Hipertrofia', 'Resistência'],
    description: 'Exercício unilateral que trabalha as pernas e glúteos, melhorando o equilíbrio e a força de cada perna individualmente.',
    instructions: [
      'Segure um halter em cada mão ao lado do corpo.',
      'Dê um passo à frente com uma perna, mantendo o tronco ereto.',
      'Abaixe o corpo até que ambos os joelhos formem um ângulo de aproximadamente 90 graus. O joelho da frente não deve ultrapassar o tornozelo.',
      'Empurre com o calcanhar da perna da frente para retornar à posição inicial.',
      'Alterne as pernas ou complete todas as repetições para uma perna antes de trocar.'
    ],
    tips: ['Mantenha o core ativado para estabilidade.', 'Controle o movimento durante a descida e a subida.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'afundo halteres',
    isCustom: false,
  },
  {
    id: 'hyperextension',
    name: 'Hiperextensão Lombar',
    emoji: '🤸',
    muscleGroup: 'Lombar',
    secondaryMuscleGroups: ['Glúteos', 'Isquiotibiais'],
    workoutType: ['Força', 'Corretivo'],
    description: 'Exercício para fortalecer os músculos da região lombar, glúteos e isquiotibiais, geralmente realizado em um banco específico.',
    instructions: [
      'Posicione-se no banco de hiperextensão, com os tornozelos seguros e o quadril apoiado na almofada.',
      'Comece com o tronco pendurado para baixo, mantendo as costas retas.',
      'Eleve o tronco até que o corpo forme uma linha reta. Evite hiperextender demais a coluna no topo.',
      'Contraia os glúteos e os músculos lombares no topo.',
      'Abaixe o tronco lentamente de volta à posição inicial.'
    ],
    tips: ['Mantenha o movimento controlado, especialmente na descida.', 'Evite arredondar as costas.', 'Pode ser feito com peso adicional (ex: anilha no peito) para aumentar a dificuldade.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'hiperextensao lombar',
    isCustom: false,
  },
  {
    id: 'hanging-leg-raise',
    name: 'Abdominal na Barra Fixa (Elevação de Pernas)',
    emoji: '🧍‍♂️',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Flexores do Quadril', 'Core'],
    workoutType: ['Força', 'Core', 'Calistenia', 'Avançado'],
    description: 'Exercício avançado para o abdômen inferior e flexores do quadril, realizado pendurado em uma barra fixa.',
    instructions: [
      'Pendure-se em uma barra fixa com as mãos na largura dos ombros e os braços esticados.',
      'Mantenha as pernas retas (ou levemente flexionadas para iniciantes).',
      'Eleve as pernas em direção ao peito, contraindo o abdômen.',
      'Tente levar os pés o mais alto possível, idealmente tocando a barra.',
      'Abaixe as pernas lentamente de volta à posição inicial, controlando o movimento.'
    ],
    tips: ['Evite balançar o corpo; use a força do abdômen.', 'Para uma variação mais fácil, comece com elevação de joelhos (joelhos dobrados).', 'Mantenha o core ativado durante todo o exercício.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abdominal barra',
    isCustom: false,
  },
  {
    id: 'dumbbell-french-press',
    name: 'Tríceps Francês com Halter',
    emoji: '💪',
    muscleGroup: 'Tríceps',
    workoutType: ['Hipertrofia', 'Força'],
    description: 'Exercício de isolamento para o tríceps, geralmente realizado deitado ou sentado, estendendo um halter (ou barra) acima da cabeça.',
    instructions: [
      'Deite-se em um banco reto ou sente-se, segurando um halter com as duas mãos (pegada em formato de taça) ou um halter em cada mão.',
      'Estenda o(s) halter(es) acima da cabeça.',
      'Mantendo os cotovelos relativamente fixos e apontando para o teto, abaixe o peso atrás da cabeça flexionando os cotovelos.',
      'Sinta o alongamento no tríceps.',
      'Estenda os braços de volta à posição inicial, contraindo o tríceps.'
    ],
    tips: ['Mantenha os cotovelos próximos à cabeça; evite que se abram para os lados.', 'Controle o peso durante todo o movimento.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'triceps frances',
    isCustom: false,
  },
  {
    id: 'barbell-romanian-deadlift',
    name: 'Stiff com Barra',
    emoji: '🦵',
    muscleGroup: 'Isquiotibiais',
    secondaryMuscleGroups: ['Glúteos', 'Lombar'],
    workoutType: ['Força', 'Hipertrofia'],
    description: 'Exercício focado nos isquiotibiais e glúteos, com ênfase no alongamento da cadeia posterior. As pernas permanecem quase retas.',
    instructions: [
      'Segure uma barra na frente das coxas com as mãos na largura dos ombros, palmas voltadas para o corpo.',
      'Mantenha as pernas quase retas (uma leve flexão nos joelhos é aceitável, mas não as dobre ativamente).',
      'Com as costas retas, incline o tronco para frente a partir do quadril, deslizando a barra pelas pernas.',
      'Desça até sentir um bom alongamento nos isquiotibiais ou até a barra chegar perto do meio da canela (ou um pouco abaixo dos joelhos).',
      'Retorne à posição inicial estendendo o quadril e contraindo os glúteos.'
    ],
    tips: ['Mantenha as costas retas durante todo o movimento; não as curve.', 'Concentre-se em empurrar o quadril para trás ao descer.', 'A barra deve permanecer próxima às pernas.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'stiff barra',
    isCustom: false,
  },
  {
    id: 'standing-calf-raise',
    name: 'Panturrilha em Pé',
    emoji: '🦵',
    muscleGroup: 'Panturrilhas',
    workoutType: ['Hipertrofia', 'Força'],
    description: 'Exercício de isolamento para os músculos da panturrilha (gastrocnêmio e sóleo), realizado em pé.',
    instructions: [
      'Fique em pé com os pés apoiados no chão ou em uma plataforma elevada (para maior amplitude).',
      'Pode ser feito com peso corporal, halteres nas mãos ou em uma máquina específica.',
      'Eleve os calcanhares o máximo possível, contraindo os músculos da panturrilha.',
      'Pause no topo por um momento.',
      'Abaixe os calcanhares lentamente, alongando as panturrilhas.'
    ],
    tips: ['Controle o movimento em ambas as direções; não use impulso.', 'Concentre-se na contração máxima no topo do movimento.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'panturrilha pe',
    isCustom: false,
  },
  {
    id: 'spider-push-up',
    name: 'Flexão Aranha',
    emoji: '🕷️',
    muscleGroup: 'Peito',
    secondaryMuscleGroups: ['Tríceps', 'Ombros', 'Core', 'Oblíquos', 'Mobilidade'],
    workoutType: ['Calistenia', 'Força', 'Mobilidade'],
    description: 'Uma variação dinâmica da flexão que envolve trazer um joelho em direção ao cotovelo do mesmo lado durante a descida, aumentando o engajamento do core e a mobilidade do quadril.',
    instructions: [
      'Comece na posição de prancha alta (mãos abaixo dos ombros, corpo reto).',
      'Ao descer para a flexão, traga o joelho direito em direção ao cotovelo direito, mantendo o pé fora do chão.',
      'Empurre de volta para a posição de prancha alta, retornando a perna direita à posição inicial.',
      'Repita do outro lado, trazendo o joelho esquerdo em direção ao cotovelo esquerdo ao descer.',
      'Alterne os lados a cada repetição.'
    ],
    tips: ['Mantenha o core ativado para evitar que o quadril caia ou gire excessivamente.', 'Tente manter o joelho o mais próximo possível do cotovelo.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'flexao aranha',
    isCustom: false,
  },
  {
    id: 'bicycle-crunches',
    name: 'Abdominal Bicicleta no Ar',
    emoji: '🚴',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Oblíquos', 'Core'],
    workoutType: ['Core', 'Resistência'],
    description: 'Exercício abdominal dinâmico que simula o movimento de pedalar uma bicicleta, trabalhando tanto os músculos abdominais superiores quanto os inferiores e oblíquos.',
    instructions: [
      'Deite-se de costas com as mãos atrás da cabeça (sem puxar o pescoço) e os joelhos dobrados em 90 graus, pés fora do chão.',
      'Levante a cabeça e os ombros do chão.',
      'Traga o cotovelo direito em direção ao joelho esquerdo enquanto estende a perna direita.',
      'Simultaneamente, traga o cotovelo esquerdo em direção ao joelho direito enquanto estende a perna esquerda.',
      'Continue alternando os lados em um movimento de "pedalar".'
    ],
    tips: ['Mantenha o movimento controlado e contínuo.', 'Concentre-se na rotação do tronco, não apenas em mover os cotovelos.', 'Evite puxar o pescoço com as mãos.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'abdominal bicicleta',
    isCustom: false,
  },
  // Novos exercícios adicionados (30)
  // Argolas
  {
    id: 'ring-row',
    name: 'Remada nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Costas',
    secondaryMuscleGroups: ['Bíceps', 'Ombros'],
    workoutType: ['Força', 'Hipertrofia', 'Calistenia'],
    description: 'Remada utilizando argolas, permite um movimento mais natural e maior ativação dos estabilizadores.',
    instructions: [
      'Ajuste as argolas a uma altura que permita inclinar o corpo para trás, mantendo os pés no chão.',
      'Segure as argolas com pegada neutra ou pronada.',
      'Mantenha o corpo reto e puxe o peito em direção às argolas, apertando as omoplatas.',
      'Desça de forma controlada. Quanto mais horizontal o corpo, mais difícil.'
    ],
    tips: ['Mantenha o core firme.', 'Não deixe os quadris caírem.', 'Foque em usar os músculos das costas para puxar.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'remada argolas',
    isCustom: false,
  },
  {
    id: 'ring-fly',
    name: 'Crucifixo nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Peito',
    secondaryMuscleGroups: ['Ombros'],
    workoutType: ['Hipertrofia', 'Calistenia'],
    description: 'Exercício de isolamento para o peito, utilizando a instabilidade das argolas.',
    instructions: [
      'Com as argolas baixas, segure-as com os braços esticados à frente do corpo, em posição de flexão.',
      'Afaste lentamente os braços para os lados, como se fosse dar um abraço, mantendo uma leve flexão nos cotovelos.',
      'Desça até sentir um bom alongamento no peito.',
      'Retorne à posição inicial contraindo o peitoral.'
    ],
    tips: ['Mantenha o core ativado.', 'Controle o movimento para evitar lesões.', 'Ajuste a inclinação do corpo para a dificuldade.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'crucifixo argolas',
    isCustom: false,
  },
  {
    id: 'ring-bicep-curl',
    name: 'Rosca Bíceps nas Argolas',
    emoji: '💪',
    muscleGroup: 'Bíceps',
    secondaryMuscleGroups: ['Antebraços'],
    workoutType: ['Hipertrofia', 'Calistenia'],
    description: 'Rosca direta utilizando argolas, focando nos bíceps com maior instabilidade.',
    instructions: [
      'Segure as argolas com pegada supinada (palmas para cima), corpo inclinado para trás.',
      'Mantendo os cotovelos fixos, puxe as argolas em direção aos ombros, contraindo os bíceps.',
      'Desça de forma controlada.'
    ],
    tips: ['Evite balançar o corpo.', 'Concentre-se na contração do bíceps.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'biceps argolas',
    isCustom: false,
  },
  {
    id: 'ring-triceps-extension',
    name: 'Extensão de Tríceps nas Argolas',
    emoji: '💪',
    muscleGroup: 'Tríceps',
    workoutType: ['Hipertrofia', 'Calistenia'],
    description: 'Extensão de tríceps utilizando a instabilidade das argolas.',
    instructions: [
      'Segure as argolas com os braços esticados acima da cabeça, corpo inclinado para frente.',
      'Mantenha os cotovelos próximos à cabeça e dobre-os, levando as mãos para trás da cabeça.',
      'Estenda os braços, contraindo o tríceps.'
    ],
    tips: ['Mantenha o core firme.', 'Não deixe os cotovelos abrirem demais.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'triceps argolas',
    isCustom: false,
  },
  {
    id: 'ring-l-sit',
    name: 'L-Sit nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Core', 'Flexores do Quadril', 'Ombros'],
    workoutType: ['Força', 'Calistenia', 'Isométrico'],
    description: 'Exercício isométrico avançado que exige muita força do core e dos ombros.',
    instructions: [
      'Suspenda-se nas argolas com os braços esticados e o corpo reto.',
      'Eleve as pernas retas à frente até formarem um ângulo de 90 graus com o tronco.',
      'Mantenha a posição pelo tempo desejado.'
    ],
    tips: ['Mantenha os ombros deprimidos (para baixo).', 'Contraia o abdômen e os quadríceps.', 'Se for difícil, comece com os joelhos dobrados (tuck L-sit).'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'lsit argolas',
    isCustom: false,
  },
  {
    id: 'ring-muscle-up',
    name: 'Muscle-Up nas Argolas',
    emoji: '🤸‍♂️',
    muscleGroup: 'Corpo Inteiro',
    secondaryMuscleGroups: ['Costas', 'Peito', 'Ombros', 'Tríceps', 'Bíceps'],
    workoutType: ['Força', 'Calistenia', 'Avançado'],
    description: 'Movimento avançado de calistenia que combina uma puxada alta com um mergulho.',
    instructions: [
      'Comece pendurado nas argolas com pegada falsa (false grip) se possível.',
      'Puxe o corpo explosivamente para cima, tentando levar o peito acima das argolas.',
      'Faça a transição dos pulsos sobre as argolas.',
      'Empurre para cima, finalizando com um mergulho (dip) até os braços estarem esticados.'
    ],
    tips: ['Requer muita força e técnica.', 'Domine pull-ups e dips nas argolas antes de tentar.', 'Mantenha as argolas próximas ao corpo durante a transição.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'muscleup argolas',
    isCustom: false,
  },
  // Rodinha Abdominal
  {
    id: 'ab-wheel-pike-rollout',
    name: 'Rollout "Pike" com Rodinha',
    emoji: '⚙️',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Ombros', 'Flexores do Quadril'],
    workoutType: ['Força', 'Core', 'Avançado'],
    description: 'Variação do rollout onde o quadril é elevado ao retornar, focando mais na parte inferior do abdômen.',
    instructions: [
      'Comece ajoelhado com a rodinha à frente.',
      'Role para frente estendendo o corpo.',
      'Ao retornar, em vez de voltar à posição ajoelhada, levante o quadril em direção ao teto, mantendo as pernas o mais retas possível (formando um "V" invertido).',
      'Controle a descida do quadril e role novamente.'
    ],
    tips: ['Mantenha o core sempre contraído.', 'Este é um exercício avançado.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'rollout pike',
    isCustom: false,
  },
  {
    id: 'ab-wheel-oblique-rollout',
    name: 'Rollout Oblíquo com Rodinha',
    emoji: '⚙️',
    muscleGroup: 'Oblíquos',
    secondaryMuscleGroups: ['Abdômen', 'Core'],
    workoutType: ['Força', 'Core'],
    description: 'Rollout direcionado para os lados, trabalhando os músculos oblíquos.',
    instructions: [
      'Ajoelhe-se com a rodinha à frente.',
      'Em vez de rolar reto, role a rodinha diagonalmente para um lado, estendendo o corpo.',
      'Retorne ao centro e repita para o outro lado.',
      'Concentre-se na contração do oblíquo do lado oposto ao movimento.'
    ],
    tips: ['Mantenha o core firme.', 'Comece com uma amplitude menor.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'rollout obliquo',
    isCustom: false,
  },
  {
    id: 'ab-wheel-plank-hold',
    name: 'Prancha com Rodinha (Isometria)',
    emoji: '⚙️',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Core', 'Ombros'],
    workoutType: ['Isométrico', 'Core'],
    description: 'Manter a posição de prancha estendida com a rodinha, desafiando a estabilidade.',
    instructions: [
      'Ajoelhe-se e segure a rodinha.',
      'Role para frente até uma posição desafiadora, mas onde consiga manter a forma correta (corpo reto, core contraído).',
      'Mantenha essa posição estática pelo tempo desejado.'
    ],
    tips: ['Não deixe a lombar arquear.', 'Respire de forma controlada.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'prancha rodinha',
    isCustom: false,
  },
  {
    id: 'single-arm-ab-wheel-rollout',
    name: 'Rollout Unilateral com Rodinha',
    emoji: '⚙️',
    muscleGroup: 'Abdômen',
    secondaryMuscleGroups: ['Oblíquos', 'Core', 'Ombros'],
    workoutType: ['Força', 'Core', 'Avançado'],
    description: 'Rollout realizado com apenas uma mão na rodinha, aumentando significativamente o desafio de estabilização.',
    instructions: [
      'Ajoelhe-se com a rodinha em uma mão.',
      'Com a outra mão apoiada no chão para equilíbrio (ou estendida para o lado), role a rodinha para frente.',
      'Retorne controladamente. Este é um exercício muito avançado.'
    ],
    tips: ['Domine o rollout com duas mãos primeiro.', 'Mantenha o core extremamente firme para evitar rotação do tronco.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'rollout unilateral',
    isCustom: false,
  },
  // Kettlebell
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    emoji: '🏋️',
    muscleGroup: 'Corpo Inteiro',
    secondaryMuscleGroups: ['Glúteos', 'Isquiotibiais', 'Lombar', 'Cardio'],
    workoutType: ['Força', 'Powerlifting', 'Condicionamento', 'HIIT'],
    description: 'Exercício fundamental com kettlebell que desenvolve potência, força e resistência, com foco no movimento de quadril.',
    instructions: [
      'Posicione o kettlebell à frente dos pés.',
      'Com as costas retas, dobre o quadril para trás e segure o kettlebell com as duas mãos.',
      'Puxe o kettlebell para trás, entre as pernas.',
      'Com um movimento explosivo do quadril (não dos braços), projete o kettlebell para frente e para cima, até a altura do peito ou ombros.',
      'Deixe o kettlebell balançar de volta entre as pernas e repita.'
    ],
    tips: ['Mantenha as costas retas o tempo todo.', 'O movimento é gerado pelo quadril, os braços apenas guiam o peso.', 'Mantenha o core firme.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kettlebell swing',
    isCustom: false,
  },
  {
    id: 'kettlebell-turkish-get-up',
    name: 'Turkish Get-Up (TGU)',
    emoji: '🏋️',
    muscleGroup: 'Corpo Inteiro',
    secondaryMuscleGroups: ['Ombros', 'Core', 'Abdômen'],
    workoutType: ['Força', 'Mobilidade', 'Estabilidade'],
    description: 'Exercício complexo que envolve levantar-se do chão para uma posição em pé enquanto se segura um kettlebell acima da cabeça.',
    instructions: [
      'Deite-se de costas, segurando o kettlebell com um braço esticado para o teto.',
      'Use o braço e a perna opostos para se apoiar e rolar para o lado.',
      'Empurre-se para uma posição sentada, depois para uma posição ajoelhada (ponte).',
      'Levante-se completamente, mantendo o kettlebell acima da cabeça o tempo todo.',
      'Reverta o movimento lentamente para voltar à posição inicial.'
    ],
    tips: ['Mantenha o olho no kettlebell durante todo o movimento.', 'Movimente-se de forma lenta e controlada.', 'Pratique sem peso ou com peso leve primeiro.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'turkish getup',
    isCustom: false,
  },
  {
    id: 'kettlebell-sumo-deadlift-high-pull',
    name: 'Sumo Deadlift High Pull (KB)',
    emoji: '🏋️',
    muscleGroup: 'Corpo Inteiro',
    secondaryMuscleGroups: ['Pernas', 'Glúteos', 'Costas', 'Ombros', 'Trapézio'],
    workoutType: ['Força', 'Condicionamento', 'CrossFit'],
    description: 'Movimento explosivo que combina um levantamento terra sumô com uma puxada alta.',
    instructions: [
      'Posicione-se com os pés mais afastados que a largura dos ombros, kettlebell no chão entre os pés.',
      'Agache com as costas retas e segure o kettlebell.',
      'Levante o peso estendendo quadris e joelhos.',
      'Continue o movimento puxando o kettlebell para cima, em direção ao queixo, com os cotovelos altos e para fora.',
      'Retorne o kettlebell ao chão de forma controlada.'
    ],
    tips: ['Mantenha o kettlebell próximo ao corpo.', 'O movimento deve ser fluido e explosivo.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sumo deadlift highpull',
    isCustom: false,
  },
  {
    id: 'kettlebell-snatch',
    name: 'Kettlebell Snatch',
    emoji: '🏋️',
    muscleGroup: 'Corpo Inteiro',
    secondaryMuscleGroups: ['Ombros', 'Costas', 'Pernas', 'Core'],
    workoutType: ['Força', 'Powerlifting', 'Condicionamento', 'Avançado'],
    description: 'Exercício avançado que move o kettlebell do chão para acima da cabeça em um único movimento fluido.',
    instructions: [
      'Comece com um swing de kettlebell.',
      'Quando o kettlebell estiver subindo, puxe-o para perto do corpo e, em seguida, "soque" a mão através da alça, finalizando com o kettlebell acima da cabeça e o braço esticado.',
      'O movimento deve ser explosivo e coordenado.'
    ],
    tips: ['Domine o swing e o clean & press antes de tentar.', 'Mantenha o kettlebell próximo ao corpo.', 'Evite que o kettlebell bata no antebraço.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kettlebell snatch',
    isCustom: false,
  },
  {
    id: 'kettlebell-windmill',
    name: 'Kettlebell Windmill',
    emoji: '🧘',
    muscleGroup: 'Oblíquos',
    secondaryMuscleGroups: ['Core', 'Ombros', 'Isquiotibiais', 'Mobilidade'],
    workoutType: ['Força', 'Mobilidade', 'Flexibilidade'],
    description: 'Exercício para core e mobilidade, onde se inclina lateralmente segurando um kettlebell acima da cabeça.',
    instructions: [
      'Segure um kettlebell acima da cabeça com um braço esticado.',
      'Pés afastados na largura dos ombros, com o pé do lado oposto ao kettlebell apontado para fora.',
      'Mantenha o braço com o kettlebell reto e olhe para ele.',
      'Dobre o quadril e deslize a mão livre pela perna em direção ao chão, mantendo as costas retas.',
      'Retorne à posição inicial.'
    ],
    tips: ['Mantenha o movimento lento e controlado.', 'Mantenha o joelho da perna da frente levemente flexionado.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kettlebell windmill',
    isCustom: false,
  },
  {
    id: 'kettlebell-halo',
    name: 'Kettlebell Halo',
    emoji: '😇',
    muscleGroup: 'Ombros',
    secondaryMuscleGroups: ['Core', 'Mobilidade'],
    workoutType: ['Aquecimento', 'Mobilidade'],
    description: 'Exercício para mobilidade dos ombros e ativação do core.',
    instructions: [
      'Segure o kettlebell pela alça com as duas mãos, com a base para cima, na frente do peito.',
      'Circule o kettlebell ao redor da cabeça, como se estivesse traçando uma auréola.',
      'Mantenha o core firme e evite mover o tronco excessivamente.',
      'Alterne a direção do círculo.'
    ],
    tips: ['Mantenha o movimento fluido e controlado.', 'Mantenha os cotovelos próximos à cabeça.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kettlebell halo',
    isCustom: false,
  },
  {
    id: 'kettlebell-figure-8',
    name: 'Kettlebell Figure 8',
    emoji: '♾️',
    muscleGroup: 'Core',
    secondaryMuscleGroups: ['Pernas', 'Ombros'],
    workoutType: ['Condicionamento', 'Coordenação'],
    description: 'Exercício dinâmico que envolve passar o kettlebell entre as pernas em um movimento de "oito".',
    instructions: [
      'Fique com os pés afastados, kettlebell em uma mão.',
      'Flexione o quadril e os joelhos, passando o kettlebell por baixo de uma perna para a outra mão.',
      'Continue o movimento, traçando um "oito" ao redor das pernas.',
      'Mantenha as costas retas e o core ativado.'
    ],
    tips: ['Mantenha o movimento fluido.', 'Evite bater o kettlebell nas pernas.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kettlebell figure8',
    isCustom: false,
  },
  {
    id: 'kettlebell-bottom-up-press',
    name: 'Kettlebell Bottom-Up Press',
    emoji: '🏋️',
    muscleGroup: 'Ombros',
    secondaryMuscleGroups: ['Antebraços', 'Core', 'Estabilidade'],
    workoutType: ['Força', 'Estabilidade', 'Avançado'],
    description: 'Pressão de ombro com o kettlebell invertido (base para cima), desafiando a força de preensão e estabilidade.',
    instructions: [
      'Segure o kettlebell pela alça com a base voltada para cima.',
      'Equilibre o kettlebell e pressione-o lentamente acima da cabeça.',
      'O controle é crucial neste exercício.'
    ],
    tips: ['Comece com um peso leve.', 'Concentre-se em manter o kettlebell equilibrado.', 'Mantenha o core firme.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kettlebell bottomup',
    isCustom: false,
  },
  // Peso Corporal
  {
    id: 'bodyweight-lunge',
    name: 'Afundo (Peso Corporal)',
    emoji: '🦵',
    muscleGroup: 'Pernas',
    secondaryMuscleGroups: ['Glúteos', 'Quadríceps'],
    workoutType: ['Força', 'Resistência', 'Calistenia'],
    description: 'Exercício unilateral para pernas e glúteos, usando apenas o peso do corpo.',
    instructions: [
      'Dê um passo à frente com uma perna.',
      'Abaixe o corpo até que ambos os joelhos formem um ângulo de 90 graus.',
      'O joelho da frente não deve ultrapassar o tornozelo, e o joelho de trás deve quase tocar o chão.',
      'Empurre com o calcanhar da perna da frente para retornar à posição inicial.',
      'Alterne as pernas.'
    ],
    tips: ['Mantenha o tronco ereto.', 'Controle o movimento.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'afundo peso corporal',
    isCustom: false,
  },
  {
    id: 'mountain-climbers',
    name: 'Escalador (Mountain Climber)',
    emoji: '🧗',
    muscleGroup: 'Core',
    secondaryMuscleGroups: ['Cardio', 'Abdômen', 'Ombros'],
    workoutType: ['Condicionamento', 'HIIT', 'Cardio'],
    description: 'Exercício dinâmico que simula o movimento de escalar, trabalhando o core e elevando a frequência cardíaca.',
    instructions: [
      'Comece na posição de prancha alta.',
      'Traga um joelho em direção ao peito, depois retorne à posição inicial.',
      'Alterne as pernas rapidamente, como se estivesse correndo no lugar.'
    ],
    tips: ['Mantenha o quadril baixo e o core ativado.', 'Não deixe o quadril subir e descer excessivamente.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'escalador exercicio',
    isCustom: false,
  },
  {
    id: 'glute-bridge',
    name: 'Ponte de Glúteos',
    emoji: '🌉',
    muscleGroup: 'Glúteos',
    secondaryMuscleGroups: ['Isquiotibiais', 'Lombar'],
    workoutType: ['Ativação', 'Força', 'Aquecimento'],
    description: 'Exercício para ativação e fortalecimento dos glúteos e isquiotibiais.',
    instructions: [
      'Deite-se de barriga para cima com os joelhos dobrados e os pés apoiados no chão, próximos aos glúteos.',
      'Mantenha os braços ao lado do corpo.',
      'Eleve o quadril em direção ao teto, contraindo os glúteos no topo.',
      'Mantenha uma linha reta dos ombros aos joelhos.',
      'Abaixe o quadril lentamente.'
    ],
    tips: ['Concentre-se na contração dos glúteos.', 'Evite arquear excessivamente a lombar.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ponte gluteos',
    isCustom: false,
  },
  {
    id: 'triceps-dip-bench',
    name: 'Mergulho no Banco (Tríceps)',
    emoji: '💪',
    muscleGroup: 'Tríceps',
    secondaryMuscleGroups: ['Peito', 'Ombros'],
    workoutType: ['Força', 'Hipertrofia'],
    description: 'Exercício para tríceps usando um banco ou cadeira.',
    instructions: [
      'Sente-se na borda de um banco, mãos apoiadas ao lado do quadril, dedos para frente.',
      'Deslize o quadril para fora do banco, apoiando o peso nas mãos.',
      'Pernas esticadas ou levemente flexionadas à frente.',
      'Dobre os cotovelos e abaixe o corpo até os cotovelos formarem um ângulo de 90 graus.',
      'Empurre de volta para cima, estendendo os braços.'
    ],
    tips: ['Mantenha os cotovelos apontados para trás, não para os lados.', 'Mantenha o corpo próximo ao banco.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'mergulho banco',
    isCustom: false,
  },
  {
    id: 'high-knees',
    name: 'Corrida com Joelhos Altos',
    emoji: '🏃‍♂️',
    muscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Pernas', 'Core'],
    workoutType: ['Aquecimento', 'Cardio', 'HIIT'],
    description: 'Exercício cardiovascular que envolve correr no lugar, elevando os joelhos o mais alto possível.',
    instructions: [
      'Corra no lugar, elevando um joelho de cada vez em direção ao peito, o mais alto que conseguir.',
      'Mantenha um ritmo rápido e contínuo.',
      'Use os braços para ajudar no movimento.'
    ],
    tips: ['Mantenha o core ativado.', 'Aterrisse suavemente na ponta dos pés.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'joelhos altos',
    isCustom: false,
  },
  {
    id: 'side-plank',
    name: 'Prancha Lateral',
    emoji: '🧍‍♀️',
    muscleGroup: 'Oblíquos',
    secondaryMuscleGroups: ['Abdômen', 'Core'],
    workoutType: ['Isométrico', 'Core'],
    description: 'Exercício isométrico que fortalece os músculos oblíquos e o core.',
    instructions: [
      'Deite-se de lado, apoiando-se no antebraço, com o cotovelo diretamente abaixo do ombro.',
      'Pés juntos ou um sobre o outro.',
      'Eleve o quadril do chão, formando uma linha reta da cabeça aos pés.',
      'Mantenha a posição pelo tempo desejado e depois troque de lado.'
    ],
    tips: ['Não deixe o quadril cair.', 'Mantenha o core firme.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'prancha lateral',
    isCustom: false,
  },
  {
    id: 'calf-raises-bodyweight',
    name: 'Panturrilha (Peso Corporal)',
    emoji: '🦵',
    muscleGroup: 'Panturrilhas',
    workoutType: ['Força', 'Resistência'],
    description: 'Exercício para panturrilhas usando apenas o peso do corpo.',
    instructions: [
      'Fique em pé, pés apoiados no chão.',
      'Eleve os calcanhares o máximo possível, contraindo as panturrilhas.',
      'Pause no topo e desça lentamente.',
      'Pode ser feito em um degrau para maior amplitude.'
    ],
    tips: ['Concentre-se na contração máxima.', 'Controle o movimento.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'panturrilha peso',
    isCustom: false,
  },
  {
    id: 'superman-exercise',
    name: 'Superman',
    emoji: '🦸',
    muscleGroup: 'Lombar',
    secondaryMuscleGroups: ['Glúteos', 'Costas'],
    workoutType: ['Força', 'Corretivo'],
    description: 'Exercício para fortalecer a região lombar e os eretores da espinha.',
    instructions: [
      'Deite-se de bruços com os braços esticados à frente e as pernas retas.',
      'Simultaneamente, levante os braços, o peito e as pernas do chão, mantendo o pescoço alinhado com a coluna.',
      'Mantenha a posição por alguns segundos e depois abaixe lentamente.',
      'Concentre-se em usar os músculos da lombar e glúteos para levantar.'
    ],
    tips: ['Evite olhar para cima para não tensionar o pescoço.', 'Mantenha o movimento controlado.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'superman lombar',
    isCustom: false,
  },
  // Elásticos (Superbands)
  {
    id: 'band-pull-apart',
    name: 'Puxada com Elástico (Pull-Apart)',
    emoji: '↔️',
    muscleGroup: 'Ombros',
    secondaryMuscleGroups: ['Costas', 'Trapézio'],
    workoutType: ['Aquecimento', 'Corretivo', 'Força'],
    description: 'Exercício para fortalecer os músculos da parte superior das costas e ombros posteriores, bom para postura.',
    instructions: [
      'Segure um elástico (superband leve ou theraband) com as duas mãos, palmas para baixo ou para dentro, braços esticados à frente na altura dos ombros.',
      'Mantenha os braços retos e puxe o elástico para os lados, afastando as mãos uma da outra.',
      'Aperte as omoplatas juntas na parte de trás do movimento.',
      'Retorne lentamente à posição inicial.'
    ],
    tips: ['Mantenha os ombros para baixo, longe das orelhas.', 'Controle o movimento, não deixe o elástico "puxar" de volta.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'band pullapart',
    isCustom: false,
  },
  {
    id: 'band-good-morning',
    name: 'Good Morning com Elástico',
    emoji: '🌅',
    muscleGroup: 'Isquiotibiais',
    secondaryMuscleGroups: ['Glúteos', 'Lombar'],
    workoutType: ['Aquecimento', 'Força', 'Mobilidade'],
    description: 'Exercício para a cadeia posterior, similar ao stiff, usando a resistência de um elástico.',
    instructions: [
      'Pise no meio de uma superband com os dois pés, afastados na largura do quadril.',
      'Passe a outra extremidade da banda por trás do pescoço, apoiando-a nos ombros/trapézio.',
      'Mantenha as pernas quase retas (leve flexão nos joelhos).',
      'Com as costas retas, dobre o quadril para frente, levando o tronco em direção ao chão.',
      'Sinta o alongamento nos isquiotibiais.',
      'Retorne à posição inicial estendendo o quadril.'
    ],
    tips: ['Mantenha as costas retas o tempo todo.', 'O movimento é uma dobradiça de quadril, não uma flexão da coluna.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'goodmorning elastico',
    isCustom: false,
  },
  {
    id: 'band-bicep-curl',
    name: 'Rosca Bíceps com Elástico',
    emoji: '💪',
    muscleGroup: 'Bíceps',
    secondaryMuscleGroups: ['Antebraços'],
    workoutType: ['Força', 'Hipertrofia', 'Resistência'],
    description: 'Rosca direta para bíceps usando a resistência de um elástico.',
    instructions: [
      'Pise no meio de uma superband com um ou dois pés.',
      'Segure as extremidades da banda com as palmas das mãos voltadas para cima.',
      'Mantenha os cotovelos próximos ao corpo.',
      'Flexione os cotovelos, trazendo as mãos em direção aos ombros, contraindo os bíceps.',
      'Abaixe lentamente, controlando a tensão do elástico.'
    ],
    tips: ['Evite balançar o corpo.', 'Ajuste a tensão pisando mais ou menos sobre a banda.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'biceps elastico',
    isCustom: false,
  },
  {
    id: 'band-glute-kickback',
    name: 'Coice com Elástico (Glúteos)',
    emoji: '🍑',
    muscleGroup: 'Glúteos',
    secondaryMuscleGroups: ['Isquiotibiais'],
    workoutType: ['Ativação', 'Força', 'Hipertrofia'],
    description: 'Exercício de isolamento para os glúteos usando um elástico (mini band ou superband).',
    instructions: [
      'Posicione uma mini band ao redor dos tornozelos ou prenda uma superband em um ponto baixo e coloque a outra extremidade no tornozelo.',
      'Fique de quatro ou em pé, apoiando-se em algo se necessário.',
      'Mantenha a perna levemente flexionada e estenda-a para trás, contraindo o glúteo.',
      'Concentre-se em "chutar" com o calcanhar.',
      'Retorne lentamente à posição inicial.'
    ],
    tips: ['Evite arquear excessivamente a lombar.', 'Concentre-se na contração do glúteo, não em levantar a perna o mais alto possível com impulso.'],
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'gluteo elastico',
    isCustom: false,
  },
];

